### ISSUE TITLE
[1.8.5] Netty IO

### ISSUE THREAD

**Issue by Bodyash** [Th3Tr0LLeR/SkinsRestorer---Maro#101]
![2016-06-18_04 47 27](https://cloud.githubusercontent.com/assets/2454569/16168449/e8fc60a6-350f-11e6-8741-c7ee81ac62db.png)
Kick when playing or trying to log in.

No problems with no SkinsRestorer.
Spigot 1.10

**Comment by Bodyash** [comment]
Buided by Blackfire

**Comment by Blackfire62** [comment]
I see, but i need some more info so i can replicate the error.
Eg. player name, online mode of the player, some other conditions...

**Comment by Bodyash** [comment]
Online mode false (Offline server)
Spigot 1.10
Java 8
player name for example - Bodyash (on login it can instatnt kick me with that error), or while playing.
Ubuntu Server 16.04
and more online > more kicks

**Comment by Dimatert9** [comment]
@Bodyash Go to skinsrestorer database, and check this player skin data.

**Comment by Blackfire62** [comment]
So far i could not replicate it because it works for me.

**Comment by Bodyash** [comment]
Wiped all DB 3 times. The same.

  bodyash:
    Value: eyJ0aW1lc3RhbXAiOjE0NjYyMzYzNjE5NzksInByb2ZpbGVJZCI6IjI5MzY0N2QyYzdlYTQwMjRiMzQzNjRjNjA1MTRjODZiIiwicHJvZmlsZU5hbWUiOiJCb2R5YXNoIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS85MThkNjE0ZjI3OTk1NTQ0MmQ1Yjc1ZjQyNmNhZjcyMmJhNTA0ZTIwZjU5MWIyZmQ4ZjBmYzIwNTFhIn19fQ==
    Signature: dBagBBmaVlbGe77nL8YWyUzjhGJneRXOvVj8ZQqxjiq+AVcR550YJT0SJQrrffUIb6pPWNqius50DIFpiyyIfBS082IVgiPancNHBxZhvCBOpHvM9wpo+tnyRxSfufxXicr9LOykCB2QQ1C402AzfUy9o3Hdzs2NvAC1DHNBVVVvK+jO7b+HuFmsDjgZ5NqnazUUGEt4HhIuCPAJsgZZDLrG8ky0kNgFGibRtPOJUm36xi5p+bo/kOAx5DhnCWSMA/9NpksQqnnfNab49j8qai54jMnSr8noh2x6mxOPJ7DZWJrFmIPw9T8xJH2JYqEpF7hcmFvGgrTuQzuX55MzWWF0qaYtVXhbe6dPiEzfEqP8bhlgT1XlkLmp47b/mTLSl7GSMCL2VhQKRLT3qNcxlAJ9ePeWnhCTHxvz/OXejoDsRo5VWzsMiXB4cg32q9OAamr20lQg187O2YbE7qYycSE0HR9I2afpQSGqNUTsm/4FJr43qRR5d3bRuVaxXv4WHP7G88UVAdV2yFSIl+RXXuj7DVAvgtRW6+dZ17UuZBPiac3iGEf2LAXSn6MDJMjmz0WXlWAhDaRNvExWk3xdbUvQp+3dn12rkJIu8ptPKBquPwNe4x4LhgjWxgblMHKVxOmcLG3Pf/9TjmgrUfPMWpLZ/bWJoh0mUNfEcXgDhl0=
    Timestamp: 1466236362073

**Comment by Bodyash** [comment]
Maybe some problems with protocollib?

**Comment by Blackfire62** [comment]
Im not even using protocol lib. 

Just to make sure its this plugin. Cretate a localhost server, with just SkinsRestorer (and all data that you currently have, i.e. move folder) and try if it does the same.

**Comment by Bodyash** [comment]
i have 2 separated servers. 1 in Russia, second and main server - in France.
In russia - windows
France - Ubuntu.

When i remove this plugin - there is no kicks from server. So i`m 100% sure that it is SR. With plugin installed - i have 7-10 kicks per hour. This bug will doesnt works with localhost and a 1 online player.
More online players - more kicks (maybe players teleporting, skins loading. i`m not sure)

**Comment by Bodyash** [comment]
![2](https://cloud.githubusercontent.com/assets/2454569/16173537/4fbcf3e0-35ac-11e6-9a97-015742865b44.PNG)
![default](https://cloud.githubusercontent.com/assets/2454569/16173536/4fba244e-35ac-11e6-98ca-937ebbe34dbf.PNG)


Some tests. Loaded SR via PLUGMAN plugin. Logged in - kicked with an netty.io error + null pointer in console.
Tried to log in second time - all is ok, skin is working. But the same null pointer in console.

**Comment by Blackfire62** [comment]
Hm, netty catches the error itself and doesnt output much more info for me. 
I will make some changes to my code so it will actually out put the entire error.

Do you use yml or mysql by the way?

**Comment by Bodyash** [comment]
Removed all data files and all SkinsRestorer plugin. Sometimes when i log in - i have EMPTY world, i need to log in /login pass.
Maybe some problems with AUTHME?

**Comment by Bodyash** [comment]
yml

**Comment by Blackfire62** [comment]
Authme, yes, authme is conflicting this plugin since 1.9 or so .

**Comment by Bodyash** [comment]
And again this netty error. So.. What i can do to fix it? I cant remove authme :C And old versions of SR is working for me GOOD at 1.9 version (now using 1.10)

**Comment by Blackfire62** [comment]
There was a setting that you could set in authme config to disable the blocking feature. 
ill see.

**Comment by Bodyash** [comment]
Blocking what? :D

**Comment by Blackfire62** [comment]
try this https://github.com/Blackfire62/SkinsRestorer---Maro/blob/master/SkinsRestorer.jar if the error will happen again, it should have some more info.

**Comment by Bodyash** [comment]
![412412](https://cloud.githubusercontent.com/assets/2454569/16173711/9e6c55c0-35b2-11e6-8abe-fe9d419f790d.PNG)
![2](https://cloud.githubusercontent.com/assets/2454569/16173712/9e6d4750-35b2-11e6-821d-6b6cc78ccb2c.PNG)
![default](https://cloud.githubusercontent.com/assets/2454569/16173713/9e6e2fee-35b2-11e6-8b91-b17e11ae6d4b.PNG)

Logged in in 5 tries. I have skin, some players cant see my skin, need relogin to see it. When player log in - there is giant chance to kick all players. So. If someone log in or tp or else - and someone see it - u will be kicked D:

**Comment by Blackfire62** [comment]
This error yet again, I cant replicate it (since im alone on my localhost) but you can try this: https://github.com/Blackfire62/SkinsRestorer---Maro/blob/master/SkinsRestorer.jar and post results.

**Comment by Bodyash** [comment]
[1.txt](https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/files/321980/1.txt)

Open it with Notepad++

Again kicks

[2.txt](https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/files/321983/2.txt)

**Comment by Blackfire62** [comment]
Hm that is aiming towards our yaml configuration, DataFiles . Id have to re-write it pretty much, since its not my work in the first place. Dunno, because rewriting it (how would i do it) would change the layout of some settings in config and locale files. So you might have to reset your config/locale then.

**Comment by Bodyash** [comment]
I`m ready to remove all SkinsRestorer folder again (i do it 3 times today)
how much time u need to write something, and how i can help u?
Im java beginer developer (just studying for 2 month, i know how to write simple classes and methods in it + object creating and using writed methods. I know about parameters too. But the biggest problem - that i dont know Spigot API at all)

**Comment by Dimatert9** [comment]
Попробуй плагин со спигота "21469". Добавь в ссылку после сайт/ресурсы/21469 . Пишу на русском чтобы авторы не обиделись)

**Comment by Blackfire62** [comment]
Add HideTablistBeforeLogin: false to authme config by the way.

**Comment by Blackfire62** [comment]
Also this error only happens if you use YML storage instead of MYSQL . You can change to mysql till fix.

**Comment by Bodyash** [comment]
@Dimatert9 Обязательно попробую, но хочу попробовать оживить этот плагин

**Comment by Bodyash** [comment]
HideTablistBeforeLogin is already set to false
