### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by ireeskenz** [Th3Tr0LLeR/SkinsRestorer---Maro#103]
Hi, i got a problem with your beautiful plugin. In fact, i'm in 1.10 and when i try to do: /skin set pseudo, it say "Can't find a valid premium player with that name". Moreover, players premium doesn't have their skins. Please can you help me ? Here is Debug.txt : http://pastebin.com/91WAw7BD

**Comment by Blackfire62** [comment]
Something is blocking the mojang API site, thats why the plugin cant acquire any data bout skins or user names. You should write to your hosting support / check the ip tables for that.

**Comment by ireeskenz** [comment]
Are you sure ? Because before in 1.9, i hadn't this problem.

**Comment by ireeskenz** [comment]
So ?

**Comment by Blackfire62** [comment]
I added alternative uuid getting url , that might work for you and others that have blocked mojang api 
https://www.spigotmc.org/threads/skinsrestorer.37225/page-93#post-1688273
