### ISSUE TITLE
Support for bukkit permissions when using bungeecord?

### ISSUE THREAD

**Issue by drizzerx** [Th3Tr0LLeR/SkinsRestorer---Maro#104]
Instead of having to use the bungeecord permissions I suggest adding code to the bukkitModule so it does this:

If players use the /skin command, the bukkitmodule will check if the player has the permission to use that command (pex,groupmanager,etc.), if the player does have the permission, the bukkit instance will tell the bungeecord instance that the player has the permission, and by that way it will allow the player to use the commands using bukkit permissions and not bungee permissions.

**Comment by Blackfire62** [comment]
Im currently planning to do this.
