### ISSUE TITLE
[REQUEST] Mojang url in variables

### ISSUE THREAD

**Issue by ashitoman** [Th3Tr0LLeR/SkinsRestorer---Maro#106]
**Can you create variables to modify mojang's URLs to create a custom web api cached  (to bypass 429 too much request)**
![url](https://cloud.githubusercontent.com/assets/19341044/16402916/0210d43e-3cb6-11e6-849f-0dc58089ef72.png)

**why?**

**because when you are limited by mojang api, the plugin can't get the UUID**
![1_429](https://cloud.githubusercontent.com/assets/19341044/16404111/8ee8156a-3cc1-11e6-8882-4b64938dff14.png)

![mensajes](https://cloud.githubusercontent.com/assets/19341044/16403920/a3300e62-3cbf-11e6-9331-0c3b4486de40.png)
![error](https://cloud.githubusercontent.com/assets/19341044/16404035/b98176aa-3cc0-11e6-8b9b-62605a06165a.png)

**this can be util for shared host where you can get 429 so fast!**

**Comment by nicuch** [comment]
Is a good ideea if you use a forum for changing skins there. (Like only 'forum' registred players can change and use the skin.)

**Comment by Blackfire62** [comment]
The alternate url one will work most of the times if Mojang API fails.

Sure, I will make it varialbe in config just like alternate skin profile url, this was just a quick fix for some people who are being rate limited and do not care about changing the url themselves.

**Comment by ashitoman** [comment]
**and when you are rate limited you don't get a NULL or EMPTY you get 
error:TooManyRequestException**
![0210d43e-3cb6-11e6-849f-0dc58089ef72](https://cloud.githubusercontent.com/assets/19341044/16417406/59399278-3d0b-11e6-80bf-14f5368e0f99.png)

**so you won't reach the altuuidurl**
add || output.contains("\"error\":\"TooManyRequestsException\"")

**Comment by Blackfire62** [comment]
Already going to added in new version, but thanks. I prolly forgot to add it when I was recoding the api from the old one, since its present in getSkinProfile .

null can only happen on internet problems, empty string means non premium player
