### ISSUE TITLE
Need some help with 1.10

### ISSUE THREAD

**Issue by FreeKillGR** [Th3Tr0LLeR/SkinsRestorer---Maro#107]
Hello can someone please tell me what I need to do to update the mod I'm a new owner so i have no idea what to do
thanks.

**Comment by Nicofisi** [comment]
Just download it, there is already a compiled version :P
https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/blob/master/SkinsRestorer-11.8.jar?raw=true

**Comment by FreeKillGR** [comment]
Thanks

**Comment by Nicofisi** [comment]
Does it work for you anyway? For me it doesn't
