### ISSUE TITLE
Error with 1.10

### ISSUE THREAD

**Issue by loonypl** [Th3Tr0LLeR/SkinsRestorer---Maro#112]
I've made '/plugins/SkinsRestorer/debug.txt' throught command /skinsrestorer debug.
Skins doesn't work, in-console nothing.
Here's code inside debug file:

http://pastebin.com/raw/iXS9A1Zk

**Comment by Blackfire62** [comment]
Something is blocking MojangAPI site, watch out for new version with new API order.
