### ISSUE TITLE
Simple Spamming Console Plugin

### ISSUE THREAD

**Issue by nicuch** [Th3Tr0LLeR/SkinsRestorer---Maro#113]
Nice and fresh error. :)
`03.07 18:06:13 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:497)
03.07 18:06:13 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03.07 18:06:13 [Server] WARN at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
03.07 18:06:13 [Server] WARN java.lang.reflect.InvocationTargetException
03.07 18:06:13 [Server] WARN Caused by: java.lang.NullPointerException
03.07 18:06:13 [Server] WARN at java.lang.Thread.run(Thread.java:745)
03.07 18:06:13 [Server] WARN at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
03.07 18:06:13 [Server] WARN at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
03.07 18:06:13 [Server] WARN at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
03.07 18:06:13 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector$5$3.run(ChannelInjector.java:340)
03.07 18:06:13 [Server] WARN at net.minecraft.server.v1_10_R1.NetworkManager$4.run(NetworkManager.java:200)
03.07 18:06:13 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
03.07 18:06:13 [Server] WARN at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
03.07 18:06:13 [Server] WARN at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
03.07 18:06:13 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
03.07 18:06:13 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
03.07 18:06:13 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
03.07 18:06:13 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
03.07 18:06:13 [Server] WARN at skinsrestorer.bukkit.listeners.SkinsPacketHandler.write(SkinsPacketHandler.java:75)
03.07 18:06:13 [Server] WARN at skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:207)
03.07 18:06:13 [Server] WARN at skinsrestorer.shared.storage.SkinStorage.getPlayerSkin(SkinStorage.java:185)
03.07 18:06:13 [Server] WARN at skinsrestorer.shared.storage.SkinStorage.removePlayerSkin(SkinStorage.java:47)
03.07 18:06:13 [Server] WARN at skinsrestorer.shared.utils.YamlConfig.set(YamlConfig.java:47)
03.07 18:06:13 [Server] WARN at skinsrestorer.shared.utils.YamlConfig.save(YamlConfig.java:119)
03.07 18:06:13 [Server] WARN at skinsrestorer.shared.utils.ReflectionUtil.invokeMethod(ReflectionUtil.java:96)
03.07 18:06:13 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:497)
03.07 18:06:13 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03.07 18:06:13 [Server] WARN at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
03.07 18:06:13 [Server] WARN java.lang.reflect.InvocationTargetException`

**Comment by Blackfire62** [comment]
Should be fixed in new version.
