### ISSUE TITLE
It is not working for 1.10 BungeeCord! it says that premium skin hypixel das not found! Any Premium skin das not found!

### ISSUE THREAD

**Issue by OWERLORD01** [Th3Tr0LLeR/SkinsRestorer---Maro#114]
Not work: "premium skin whit that name das not found"
I can change skin with admin commands,but player command /skin set das not working!

**Comment by Th3Tr0LLeR** [comment]
Interesting

**Comment by ashitoman** [comment]
Player commands: (skinsrestorer.playercmds)
/skin <skinname> - Sets your skin

**Comment by Blackfire62** [comment]
ashitoman is right, since there is no longer a "set" parameter

**Comment by AmazedMender16** [comment]
it keeps on crashing whenever a player joins and kicks everyone
