### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by nicuch** [Th3Tr0LLeR/SkinsRestorer---Maro#116]
Why you don't create 3x jars for every server type? i think is better :) one for spigot, one for sponge and one for bungeecord.
for example, in spigot you can use [YamlConfiguration](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/configuration/file/YamlConfiguration.html) :)

**Comment by Blackfire62** [comment]
Not really, and we are indeed using YamlConfiguration if the plugin is ran with Bukkit/Spigot.
