### ISSUE TITLE
Why do you need to save skins?

### ISSUE THREAD

**Issue by MatteCarra** [Th3Tr0LLeR/SkinsRestorer---Maro#119]
I have this curiosity
Why do you need to save skins?

**Comment by nicuch** [comment]
need to save signature i think, btw they can use a new class for saving... i think
public class User {
 private final String signature;
 private final String name; //private final UUID uuid;

 public User (Player player, String signature) {
 this.signature = signature;
 this.name = player.getName();
 }

 public String getSignature() {
 return this.signature;
 }
}

i think is much better, but whatever

**Comment by Blackfire62** [comment]
Skins are acquired by calling MojangAPI url like this : 

Getting the username UUID from:
https://api.mojang.com/users/profiles/minecraft/NAME
and then the skin data from:
https://sessionserver.mojang.com/session/minecraft/profile/UUID?unsigned=false

Try it out yourself. The first API has little to no restrictions on usage (no more than 100 requests at once) but the second one has a delay (10 minutes) between getting skin data of the same player.

Thats why we save the skin data to a file, to instantly apply skin upon joining, and after joining we can try to get a fresh skin data from the api and even if it fails for whatever reason, we can still have a skin!


Also, the code above is pretty much whatever, but its pointless to save it in memory when you can just use a file or mysql. Also ConcurrentHashMap exists, it doesnt allow null keys and does all the synchronization between thread calls on its own, saves work.

**Comment by nicuch** [comment]
is a problem with nullpointerexceptions and because you set skin signature empty will kick all players from server

**Comment by Blackfire62** [comment]
Empty signature and or value just means no skin -> default skin (steve/alex) .
You can crash a player with setting corrupted skin data to him, the worst that can happen is he will get disconnected from server because you set either value or signature to null explicitly.
