### ISSUE TITLE
Could not pass PlayerJoinEvent to SkinsRestorer

### ISSUE THREAD

**Issue by Eufranio** [Th3Tr0LLeR/SkinsRestorer---Maro#128]
https://github.com/Shevchik/SkinsRestorer/issues/35
Using Thermos (kCauldron fork)

**Comment by Blackfire62** [comment]
Welp I dont fully support Thermos since I barely have any idea how packets in it work. Skins should work but the instant chaning should not. I will get rid of this error next update.

**Comment by Eufranio** [comment]
Okay, waiting :smile:
