### ISSUE TITLE
Redis support needed

### ISSUE THREAD

**Issue by DragonbornCommunity** [Th3Tr0LLeR/SkinsRestorer---Maro#129]
Two players in different bungee instances can't see each other's skin, while 2 players on the same bungeecord instance can see each others'. I think this problem is related to a lack of Redisbungee support.

Hope you will add Redisbungee support, we will surely consider donating after such update.

**Comment by Blackfire62** [comment]
It could be. SkinsRestorer can only handle its own bungee instance and its players.

And RedisBungee is a premium resource, so, I do not have it.

**Comment by elraro** [comment]
https://github.com/minecrafter/RedisBungee

Its free
