### ISSUE TITLE
error in console and skin not work

### ISSUE THREAD

**Issue by SliderKP** [Th3Tr0LLeR/SkinsRestorer---Maro#131]
Bungee and spigot servers the errors occours in the bungee console:

02:20:10 [SEVERE] java.lang.NoSuchFieldException: loginProfile
02:20:10 [SEVERE]     at java.lang.Class.getField(Class.java:1703)
02:20:10 [SEVERE]     at skinsrestorer.shared.utils.ReflectionUtil.getField(ReflectionUtil.java:30)
02:20:10 [SEVERE]     at skinsrestorer.shared.utils.ReflectionUtil.setObject(ReflectionUtil.java:48)
02:20:10 [SEVERE]     at skinsrestorer.bungee.SkinApplier$1.run(SkinApplier.java:40)
02:20:10 [SEVERE]     at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
02:20:10 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
02:20:10 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
02:20:10 [SEVERE]     at java.lang.Thread.run(Thread.java:745)

**Comment by Qveshn** [comment]
Had the same error

**Comment by Blackfire62** [comment]
You must be either using a very old version of bungee or a different fork that does not have loginProfile. What do you use?

**Comment by SliderKP** [comment]
yes i can't use the latest bungee version... i'm using Bungee #1087 (1.8)

**Comment by Blackfire62** [comment]
I got SkinsRestorer working fine with your Bunge 1087
http://image.prntscr.com/image/7b53814f91984cff8b5acfb80b4ce1ba.png

**Comment by SliderKP** [comment]
server in online mode=false?

but you try to join the server and see  your skin and change it?
The errors occours when a users join to the server... and when try to change skin.
