### ISSUE TITLE
[Bungee] ApplySkin error.

### ISSUE THREAD

**Issue by plasmavngaming** [Th3Tr0LLeR/SkinsRestorer---Maro#133]
I Found this Error when I use API for my Plugin
`16:04:59 [SEVERE] java.lang.NullPointerException
16:04:59 [SEVERE] 	at skinsrestorer.shared.utils.ReflectionUtil.getMethod(ReflectionUtil.java:76)
16:04:59 [SEVERE] 	at skinsrestorer.shared.utils.ReflectionUtil.invokeMethod(ReflectionUtil.java:145)
16:04:59 [SEVERE] 	at skinsrestorer.shared.api.SkinsRestorerAPI.applySkin(SkinsRestorerAPI.java:93)
16:04:59 [SEVERE] 	at com.gmail.themasterclaus.DSBC.Main$2.run(Main.java:79)
16:04:59 [SEVERE] 	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
16:04:59 [SEVERE] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
16:04:59 [SEVERE] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
16:04:59 [SEVERE] 	at java.lang.Thread.run(Unknown Source)`

And this is my code

> 	public void changeRequest(PluginMessageEvent e) {
		if (!e.getTag().equals("DSBC"))
			return;
		ByteArrayInputStream stream = new ByteArrayInputStream(e.getData());
		DataInputStream in = new DataInputStream(stream);
		try {
			final String[] data = in.readUTF().split("-skin-");
			final ProxiedPlayer p = getProxy().getPlayer(data[0]);
			if (p == null)
				return;
			getProxy().getScheduler().runAsync(this, new Runnable() {
				@Override
				public void run() {
					try {
						SkinsRestorerAPI.setSkin(data[0], data[1]);
						SkinsRestorerAPI.applySkin(p);
						
						p.sendMessage(new TextComponent("§aĐổi Skin thành công!"));
					} catch (Exception e1) {
						p.sendMessage(
								new TextComponent("§cĐã có lỗi xảy ra, hãy thử lại."));
					}
				}
			});
		} catch (IOException e1) {
		}
	}

**Comment by Blackfire62** [comment]
Will be fixed in next dev build, thanks for reporting this api error along with others.
