### ISSUE TITLE
Command Block issue

### ISSUE THREAD

**Issue by Danielix99** [Th3Tr0LLeR/SkinsRestorer---Maro#134]
Hi, i'm using your SkinRestorer plugin for my 1.10 spigot server, i dont have any plugin except your because this server its only for my friends, then if your plugin is on i cant edit, place, use the command block, but if i turn it off, all work perfectly, can you help me??

**Comment by Th3Tr0LLeR** [comment]
Seems strange, Doesn't have such problem through
