### ISSUE TITLE
API - java.lang.NoClassDefFoundError Error on Bungee

### ISSUE THREAD

**Issue by TagCraftMC** [Th3Tr0LLeR/SkinsRestorer---Maro#141]
The [SkinRestorerAPI class](https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/blob/master/src/skinsrestorer/shared/api/SkinsRestorerAPI.java) uses _org.apache.commons.io.output.ByteArrayOutputStream_ which causes a _java.lang.NoClassDefFoundError_ error when using the method _SkinsRestorerAPI.setSkin()_ in bungeecord.

**Bungee:** 1175
**SR:** v12.5.8
**Error:** http://pastebin.com/Gdn1tMDb

Thanks!

**Comment by Th3Tr0LLeR** [comment]
Thanks. WIll look into that.
