### ISSUE TITLE
download 1.8?

### ISSUE THREAD

**Issue by MCG-server** [Th3Tr0LLeR/SkinsRestorer---Maro#142]
You could spend the latest version 1.8 of skinsrestorer for spigot (1.8) and bungeecord (1.8) ... thanks in advance

**Comment by Th3Tr0LLeR** [comment]
What ?

**Comment by MCG-server** [comment]
if you can give me the link of the latest version 1.8
plugins ( for spigot 1.8 . and 1.8 bungeecord ) perxhe on the spigot site does not bring to that version is the plugin
