### ISSUE TITLE
Player clones bug

### ISSUE THREAD

**Issue by TerZer** [Th3Tr0LLeR/SkinsRestorer---Maro#143]
I using skinrestorer, everything works great, but some times people leave "skin clones"

**Comment by phil568622** [comment]
Same problem here, sometimes there are also people on our tab list that are not online on the Server

**Comment by TerZer** [comment]
I don't have tablist problem, just sometimes people clones.

**Comment by Platinteufel** [comment]
Same issue here. @Blackfire62 managed to fix this in 11.8, but now it's happening again. 

"[...] Also your clone on bukkit servers is caused by not removing the player before adding it again properly. Since Ive done it all in reflection, it may take me a little bit of time to fix it (and considering the fact I barely got any time at all)."

+				sendPacket(playerCon, removeEntity);
+				sendPacket(playerCon, removeInfo);
 
+				sendPacket(playerCon, addInfo);
+				sendPacket(playerCon, addNamed);

**Comment by Platinteufel** [comment]
Let's compare the packet updating codes.
Fix from @Blackfire62: https://github.com/Blackfire62/SkinsRestorer---Maro/blob/a651874de9efddb6e8510387954691a6c5f36dbc/src/skinsrestorer/bukkit/UniversalSkinFactory.java#L289
Chaged from @Th3Tr0LLeR: https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/blob/master/src/skinsrestorer/bukkit/skinfactory/UniversalSkinFactory.java#L287

**Comment by Platinteufel** [comment]
Okay, seems like this is not caused by updating packets. Maybe it happens on logout?

**Comment by phil568622** [comment]
Yep, pretty sure it happens on logout. I was afk for about 1 hour and then saw 4 Ghost players Standing around, I checked /seen and they all were offline for less than an hour.

Also, the Ghost players disappear when you fly away and the Chunk is out of your render distance. When you re-enter the Chunk the Ghost player is gone.

**Comment by phil568622** [comment]
There also may be a Problem on login, but I don't know and I cant test it right now.

**Comment by molor** [comment]
Spigot 1.10.2, same problem.. When will be fix?

**Comment by Th3Tr0LLeR** [comment]
I don't really know.

2016-08-25 20:05 GMT+03:00 Evgeniy <notifications@github.com>:

**Comment by Platinteufel** [comment]
@Th3Tr0LLeR: Try to check the logout listener if you have time. 
Seems like skin data is not always removed correctly on player quit, especially if the player doesn't login with AuthMe **/login**, but rather waits a few seconds till AuthMe kicks he/she for login timeout.

**Comment by Th3Tr0LLeR** [comment]
Yeah, That could be a good reason. I will check that out.

**Comment by Th3Tr0LLeR** [comment]
@phil568622 They dissapear, because it's client side. It also happens if player logs in/out too fast.
