### ISSUE TITLE
skinrestorer Overloading bungeecord? 

### ISSUE THREAD

**Issue by BoomEaro** [Th3Tr0LLeR/SkinsRestorer---Maro#144]
Spam in log file BungeeCord:
10:21:23 [INFO] xX_Riste_xX executed command: /skin poop
10:21:46 [INFO] xX_Riste_xX executed command: /skin YusufKorkut
10:21:48 [INFO] xX_Riste_xX executed command: /skin YusufKorkut
10:21:48 [INFO] xX_Riste_xX executed command: /skin YusufKorkut
10:21:49 [INFO] xX_Riste_xX executed command: /skin YusufKorkut
10:21:49 [INFO] xX_Riste_xX executed command: /skin YusufKorkut
10:21:50 [INFO] xX_Riste_xX executed command: /skin YusufKorkut
10:21:50 [INFO] xX_Riste_xX executed command: /skin YusufKorkut
10:21:51 [INFO] xX_Riste_xX executed command: /skin YusufKorkut
10:21:51 [INFO] xX_Riste_xX executed command: /skin YusufKorkut
10:21:52 [INFO] xX_Riste_xX executed command: /skin YusufKorkut
10:21:52 [INFO] xX_Riste_xX executed command: /skin YusufKorkut
10:21:53 [INFO] xX_Riste_xX executed command: /skin YusufKorkut
10:21:54 [INFO] xX_Riste_xX executed command: /skin YusufKorkut
10:21:54 [INFO] xX_Riste_xX executed command: /skin YusufKorkut
10:21:55 [INFO] xX_Riste_xX executed command: /skin YusufKorkut
10:21:56 [INFO] xX_Riste_xX executed command: /skin YusufKorkut
10:21:56 [INFO] xX_Riste_xX executed command: /skin YusufKorkut
10:21:57 [INFO] xX_Riste_xX executed command: /skin YusufKorkut
10:21:59 [INFO] xX_Riste_xX executed command: /skin YusufKorkut
10:21:59 [INFO] xX_Riste_xX executed command: /skin YusufKorkut

After spam, disconnection of all players on the server:
[10:23:17] [Server thread/INFO]: superisrali lost connection: Disconnected
[10:23:17] [Server thread/INFO]:  superisrali [-]
[10:23:17] [Server thread/INFO]: _Mr_Frost lost connection: Disconnected
[10:23:17] [Server thread/INFO]:  _Mr_Frost [-]
[10:23:17] [Server thread/INFO]: xX_Riste_xX lost connection: Disconnected
[10:23:17] [Server thread/INFO]:  xX_Riste_xX [-]
[10:23:17] [Server thread/INFO]: Sharon lost connection: Disconnected
[10:23:17] [Server thread/INFO]:  Sharon [-]
[10:23:17] [Server thread/INFO]: sonicexe lost connection: Disconnected
[10:23:17] [Server thread/INFO]:  sonicexe [-]
[10:23:17] [Server thread/INFO]: Luigi lost connection: Disconnected
[10:23:17] [Server thread/INFO]:  Luigi [-]

Skinrestorer latest version
BungeeCord latest build 
Serrver Spigot 1.8.* 

This is a bug or problem BungeeCord?

(sorry for my english)

**Comment by Th3Tr0LLeR** [comment]
Well, the command should have a cooldown. make sure you enable it.

**Comment by BoomEaro** [comment]
The delay is, everything works.
Reviewing the "timings" I realized that the problem is not with your plugin :)
Problem was plugin simpleclans, it turned out that every 20 minutes a mistake.
And so it happened that someone spamming command, and when the error occurred, and kicked all.

Could you add the countdown until the next use of the command / skin <skinname>?

Example: you have to wait for another 30 seconds, which would run the command
And if once again to write the command, then you will have to wait another 28 seconds that would execute the command.
It will be more convenient and informative. And you'll have to find out at random times to use the new command.

sorry for my English

**Comment by Th3Tr0LLeR** [comment]
Yeah, that could be done.
