### ISSUE TITLE
kcauldron errors

### ISSUE THREAD

**Issue by aglarcz** [Th3Tr0LLeR/SkinsRestorer---Maro#145]
Hello guys,
i know you are not supporting kcauldron 1.7.10 because of packet issue but would it be possible to get rid of this error? http://pastebin.com/7Nr9fgYN

Plugin is working properly, only cracked players doesnt see their own skin but its ok - would it be possible to just hide this error in console somehow or make some custom jar for kcauldron so it would stop spamming this in console after every joined player?

**Comment by Th3Tr0LLeR** [comment]
Well, we don't support kcauldron for other reasons too. That's bad.
