### ISSUE TITLE
Dropped and default skins

### ISSUE THREAD

**Issue by WarGamesServer** [Th3Tr0LLeR/SkinsRestorer---Maro#147]
The dropped and the default skins don't be modified when it configure.
I use WaterFall and this is the config.yml:
###### 
# This option disables automatic requesting & applying skins on join
# Commands still work

DisableOnJoinSkins: false
# This is for preventing skin change spam

SkinChangeCooldown: 15
# Mojang API (Used to get our skin data) has request limit:
# You can only request skin data of the same player only once in 10 minutes
# 
# To bypass this, here are some our default alternative APIs to get the skin data
# Feel free to change them to your own

Alternatives:
  SkinPropertyURL: https://mcapi.ca/name/uuid/
  NEWUUID: http://mcapi.ca/uuid/player/
# Enable or disable default skins
# If more nicknames will be in the list, server will
# always choose a random one

DefaultSkins:
  Enabled: true
  Names:
    - wargames
    - war101
# Disable skin names
# Put skins you want to disable on the list
# Player wont be able to set these skins

DisabledSkins:
  Enabled: true
  Names:
    - wargames
    - war101
# Multi-Bungee support
# If you use more proxy servers and you
# experience issues with skin visibility between proxies
# enable this option
# 
# RedisBungee enables this option automatically

MultiBungee:
  Enabled: false
# MySQL database for large servers
# or just to boost the performance

MySQL:
  Enabled: true
  Host: localhost
  Port: 3306
  Database: SkinsRestorer
  SkinTable: Skins
  PlayerTable: Players
  Username: root
  Password: pass

Updater:
  Enabled: true
# Enable or disable the updater check on enable.

**Comment by Th3Tr0LLeR** [comment]
I believe that option no longer works.

**Comment by WarGamesServer** [comment]
Can you readd this function?

**Comment by Th3Tr0LLeR** [comment]
Maybe
