### ISSUE TITLE
Instant skin updating

### ISSUE THREAD

**Issue by Platinteufel** [Th3Tr0LLeR/SkinsRestorer---Maro#148]
I'm running the latest paper spigot and latest skinsrestorer and if I type /skin name I'll see my old skin until I relog, but the other players around me will see the new skin instant. 
There are a lot of players that reported this issue to me too. 
I've upgraded from an older version and I remeber that it worked perfectly there.

**Comment by Th3Tr0LLeR** [comment]
Let me check that out.

**Comment by Th3Tr0LLeR** [comment]
Everything seems to work fine. Can you show me debug file ? There could be some conflicting plugins.

**Comment by Platinteufel** [comment]
Okay, I've also looked into it. Seems like this is a client-side issue that happens random in very rare cases. Nothing to fix on your side. Thank you tho!
