### ISSUE TITLE
[API] Another Issue. BungeeCord - org/bukkit/plugin/Plugin

### ISSUE THREAD

**Issue by TagCraftMC** [Th3Tr0LLeR/SkinsRestorer---Maro#149]
Hi Th3Tr0LLeR,

Another issue with the API.
When trying to access SkinsRestorerAPI.setSkin(Player, String) via bungecord it throws an "java.lang.NoClassDefFoundError: org/bukkit/plugin/Plugin" error.

I am using version 12.6.1 on the server and within the project and the Player is ProxiedPlayer

Code Snip-it:
`
SkinsRestorerAPI.setSkin(player.getName(), skin); //not working currently.
if (player != null)
{
	SkinApplier.applySkin(player);
}
`

Full Error: (line 48 is what's above) http://pastebin.com/s21PXBvX

Thanks.

**Comment by Th3Tr0LLeR** [comment]
That again ? Fok :D I will fix it.

**Comment by games647** [comment]
@Th3Tr0LLeR You should maybe seperate the bukkit, bungee, core from each other. Then you don't run into these pitfalls.

**Comment by Th3Tr0LLeR** [comment]
@games647 That's exactly what i did, but then BlackFire made them in one class again. :D

**Comment by games647** [comment]
No I even meant to seperate the project into different project. Example: bukkit modules doesn't see the dependency of BungeeCord and therefore you can't import it by mistake.

**Comment by Th3Tr0LLeR** [comment]
Yeah. That'd be good, but at the time I'm working like this. Also i already fixed that :D (twice) since it didnt fix the first time.

**Comment by Th3Tr0LLeR** [comment]
@games647 Fixed that too i believe.
