### ISSUE TITLE
[Bungee] SkinsRestorer doesn't work on OnlineMode

### ISSUE THREAD

**Issue by games647** [Th3Tr0LLeR/SkinsRestorer---Maro#151]
For FastLogin, some players are in onlinemode. If I choose a custom skin using /skin name. I cannot see the skin. I tested it with and without the forwardSkin of FastLogin. In both cases I don't see the skin of SkinsRestorer, but because of the EvenPriority FastLogin doesn't override the skin of SkinsRestorer.

After I attached the debugger and set a couple of breakpoints, I found out that this [check](https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/blob/master/src/skinsrestorer/bungee/SkinApplier.java#L27) is the source of it. I removed it and it worked. I could see the custom skin of SkinsRestorer. 

Tested with:
FastLogin 1.8
SkinsRestorer 12.7 

Maybe you take a look into it, because you know your code better.

**Comment by Th3Tr0LLeR** [comment]
That's because SkinsRestorer doesn't need to forward premium skins, because the players already have them. However, this is affecting the /skin name command and i will also remove that check.

Thanks.

**Comment by Th3Tr0LLeR** [comment]
https://www.spigotmc.org/resources/skinsrestorer.2124/update?update=114587 Baye. Thanks for that issue.

P.S. These versions are still snapshots and they are pretty unstable.
