### ISSUE TITLE
Problem with ProtocolSupport

### ISSUE THREAD

**Issue by RevengeForceBG** [Th3Tr0LLeR/SkinsRestorer---Maro#153]
New versions have problem with protocolsupport when join player on 1.5.2-1.7.x Minecraft client is crashed reason is skinsrestorer oldest not have this problem.Please fix it Thx!

**Comment by Th3Tr0LLeR** [comment]
Older versions won't be supported anymore. I just left the 1.7 support there, because it will be rude if i removed it.
