### ISSUE TITLE
SkinRestorer Permissions

### ISSUE THREAD

**Issue by Rodrogamby** [Th3Tr0LLeR/SkinsRestorer---Maro#156]
SkinRestorer permissions are not working!, I'm using bungee, SkinRestorer is in /plugins, I added the permission skinsrestorer.cmds to config.yml, nothing happened, please answer.

**Comment by Th3Tr0LLeR** [comment]
skinsrestorer.playercmds is required too <3

**Comment by LazerFighter12** [comment]
where do i need to put the permissions node

**Comment by Rodrogamby** [comment]
Thank you! 👍

**Comment by Rodrogamby** [comment]
LazerFighter12, you need to put the permissions inside config.yml on the bungee folder.

**Comment by alek-shirar** [comment]
the commands are enabled by default for anyone to use... any player can change their skin.
skinsrestorer.playercmds not having any effect on being -skinsrestorer.playercmds in permissions.yml (specified disabled)

**Comment by xknat** [comment]
@alek-shirar this has been fixed on our dev branch: https://github.com/DoNotSpamPls/SkinsRestorerX/
