### ISSUE TITLE
[Feature] Disable Skin Update/Checks

### ISSUE THREAD

**Issue by TagCraftMC** [Th3Tr0LLeR/SkinsRestorer---Maro#158]
Hoping to get a feature added that stops the plugin trying to obtain the latest version of a skin.

The set up I have is, anyone whom joins my network that has no skin is assigned a custom skin. This skin is a random name (non premium) with the skin value and signature I want.
This set up works work for around the first 1-3 days, then it's as if the plugin tries to get the latest skin for that account name and sees that its not a real account so it clears the value and signature fields for that row.

I can "fix" it by re-adding the value and signature to the name in the database again, but it requires me to restart the bungeecord server for it to take effect (or /sr reload). It would be great if there was a new column (Boolean) that would make the skin permanent (non updated) if set to true.  

Thanks.

**Comment by Th3Tr0LLeR** [comment]
That's good idea. Thanks.

**Comment by xknat** [comment]
has been done way back lel
