### ISSUE TITLE
Still have crash issues

### ISSUE THREAD

**Issue by Kira07** [Th3Tr0LLeR/SkinsRestorer---Maro#161]
I run paperspigot 1.7.10 protocolhack and a player playing in 1.8 gave me his crash report: http://m.uploadedit.com/ba3s/1477499489332.txt
(often in combat)

**Comment by xknat** [comment]
we give no longer support to 1.7 sins the plugin was mean to work on 1.8

**Comment by Kira07** [comment]
Then please remove the "1.7" mention on the plugins page and make it clear
that the support was removed.
It is quite annoying as there are still a lot of 1.7 servers and no viable
alternative to your plugin, you could make a paid version with 1.7 support,
I'd pay for it.

2016-10-28 20:17 GMT+01:00 xknat <notifications@github.com>:

**Comment by Th3Tr0LLeR** [comment]
No. I can not. If 1.7 support without crashes was possible i could made it, but i can't solve this crashes. I tried so many times and i failed on that. Just a note that I am not a professional programmer, so i can not solve too much issues related to the plugin. I may try one more time and if i fail. I will totally remove the 1.7 support from the page and from the plugin.

**Comment by Kira07** [comment]
I see... It would be great, If it can help you the bug is pretty recent, it
never happened with the old versions, I think it's somethong you
added/changed.

2016-10-28 21:22 GMT+01:00 Th3Tr0LLeR <notifications@github.com>:

**Comment by Th3Tr0LLeR** [comment]
It's caused by skull rendering. I am working on a fix for that thing right now. Add me on skype marin.maniaka if you can.

**Comment by Kira07** [comment]
Thank you, I already have you in my contacts, I just PM'd you.

2016-10-28 21:44 GMT+01:00 Th3Tr0LLeR <notifications@github.com>:
