### ISSUE TITLE
[Feature] Thermos support

### ISSUE THREAD

**Issue by Lmmb74** [Th3Tr0LLeR/SkinsRestorer---Maro#162]
Could you please add it? Plsss

**Comment by Th3Tr0LLeR** [comment]
Nope.

2016-10-28 19:59 GMT+03:00 Lmmb74 <notifications@github.com>:

**Comment by Lmmb74** [comment]
U.u ok but could you tell me why?

**Comment by Th3Tr0LLeR** [comment]
Yes. It's because i tried and i can't figure out how to send the needed
packets without a mod.

2016-10-29 0:01 GMT+03:00 Lmmb74 <notifications@github.com>:

**Comment by Lmmb74** [comment]
Ok t.t
