### ISSUE TITLE
Can you fix skull item?

### ISSUE THREAD

**Issue by iRandomXx** [Th3Tr0LLeR/SkinsRestorer---Maro#165]
I use bungeecord 1.8.8 with ur plugin installed on it.
But for the last version of SkinsRestorer when i create a skullitem, the skull doesn't have a skin or print a error on the console (couldn't lookup gameprofil, too many request)

Spigot issue or can you fix this?
Thanks, sorry for my bad language i'm french.

**Comment by xknat** [comment]
[for help on this click HERE](https://discord.me/skinsrestorer)
