### ISSUE TITLE
Skins don't show

### ISSUE THREAD

**Issue by BlackRavenMC** [Th3Tr0LLeR/SkinsRestorer---Maro#17]
My friends can see my skin, but I can't, no one can see their own skin. I have bungee and 2 other servers. I'm using 11.0-v2 skinrestorer.

**Comment by Blackfire62** [comment]
Did you put SkinsModule, that is in the downloaded ZIP file, in those servers plugins?

**Comment by BlackRavenMC** [comment]
Figured it out, it was Authme that caused that. Now secound question, why now no one have skins. Even this don't [Skins](https://mcapi.ca/SR/?player=Notch).

**Comment by Th3Tr0LLeR** [comment]
I've had this issue too. Dunno what causes it, but i will be working on a fix.

**Comment by BlackRavenMC** [comment]
One day skins work for only hour and then again broken.

**Comment by belfedia** [comment]
Please how can i handle the authme problem ?

**Comment by BlackRavenMC** [comment]
@belfedia, set HideTablistBeforeLogin to false.

**Comment by belfedia** [comment]
Thanks you solve all my problem with SkinsRestorer :)
A simple sentence "User of authme5.2 must to put in authme config : "HideTablistBeforeLogin false"
can help many people :/

**Comment by Blackfire62** [comment]
Yeah, but we already stated that its a known authme problem (My post some time ago) , and you decided to ignore it and blame SR instead. Well, this issue is done.

**Comment by belfedia** [comment]
Don't blame SR ! it was clear, it's a Authme problem, but just WARN ! Many people search why they have this bug, and a warn message on overview can help him, no ?
