### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by NelsonHD** [Th3Tr0LLeR/SkinsRestorer---Maro#171]
SkinsRestorer 12.9.4 + BungeeCord 1.8.x + Spigot 1.8.x
All player's skin are steve, cant see their own skin

**Comment by Th3Tr0LLeR** [comment]
+100% sure you're using ProtocolLib or ViaVersion

**Comment by NelsonHD** [comment]
Which ProtocolLib ? Bungeecord or Spigot ?

**Comment by NelsonHD** [comment]
fixed
