### ISSUE TITLE
Random kicks

### ISSUE THREAD

**Issue by Nishh** [Th3Tr0LLeR/SkinsRestorer---Maro#172]
Server side log:
just "player lost connection: Disconnected"

Client side kick message:
"com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1"
and sometime:
"java.util.NoSuchElementException: packet_handler"

Plugins: http://pastebin.com/Hh0e1RQ6
Server version: Paper-842 (1.10.2 PaperSpigot)
SkinsRestorer version: latest (12.9.4)
No problem in version: 12.8.5

random kicks stopped when SkinsRestorer removed.

**Comment by Gerolfing** [comment]
I have same issue. Already joined players are kicked when another player joins the server. In server console it shows "player disconnected" and in client io netty error like on  screenshot http://i.imgur.com/XrYeDU1.jpg

**Comment by TheIntelloBox** [comment]
I agree. I had the same problem on Spigot 1.8. :( Fix it soon please. :)

**Comment by stan60250** [comment]
I have same issue too. Random kicks online player when someone join the server.

Client side kick message(from different player):
http://imgur.com/a/dBy1H

Plugins: Only SkinsRestorer v12.9.4
Server version: Spigot 1.11 (latest)

**Comment by AmazedMender16** [comment]
Same issue!

**Comment by Gerolfing** [comment]
The workaround is to stay on older version, I am currently on 12.8.5 and it works ok on 1.11, but have duplicate bug, puplicated players stand on spawn.

**Comment by 030Amber** [comment]
I've encountered the same issue. Please fix this, thanks!

**Comment by 030Amber** [comment]
http://imgur.com/hRgxfh8

Screenshot here. Hope it helps fixing the bug.

**Comment by TheIntelloBox** [comment]
I contacted the author. He says that he hasn't the time for this update. 

I'm using 12.8.5 and it's works fine on 1.11.

**Comment by 030Amber** [comment]
Good. Using 12.8.5 now, no bugs. 12.9 and up have the issue.

**Comment by stan60250** [comment]
I'm using 12.9.5 now and it works fine on PaperSpigot 1.11.
Link: https://github.com/Blackfire62/SkinsRestorer---Maro
(Need to compile it yourself)

**Comment by TheIntelloBox** [comment]
0 problem with kick ?

**Comment by stan60250** [comment]
Yes, but I only test on Spigot/PaperSpigot 1.11.

**Comment by TheIntelloBox** [comment]
Okay, I'm using Spigot 1.11 too. Could you compile it ?

**Comment by xknat** [comment]
for support join our discord server! [https://discord.me/skinsrestorer](https://discord.me/skinsrestorer)
