### ISSUE TITLE
API does not work

### ISSUE THREAD

**Issue by Xayanix** [Th3Tr0LLeR/SkinsRestorer---Maro#177]
Error: http://scr.hu/0duk/kjoih
Version: 1.7.10 (tried on 1.11.2 and it's same).

Code of plugin:
String skin = SkinsRestorerAPI.getSkinName(nick);
SkinsRestorerAPI.setSkin(player.getName(), skin);
SkinsRestorerAPI.applySkin(player);

**Comment by xknat** [comment]
for support, join our discord support server! [https://discord.me/skinsrestorer](https://discord.me/skinsrestorer)
