### ISSUE TITLE
SkinsRestorer not working anymore.

### ISSUE THREAD

**Issue by MinecraftKid45** [Th3Tr0LLeR/SkinsRestorer---Maro#178]
I have used SkinsRestorer probably since it came out, I have never had any issues except once like this and I don't remember how I fixed it, I think the API was under maintenance, but now it's not working at all.
The API states it has been removed for causing more trouble then it's worth fixing...
So, I can't get Skins through the normal Mojang API cause of "Rate Limited", even though I haven't done anything, I guess Mojang doesn't want your server to get lots of players.

Can you please inplement another API? Cause in the newest version there is no option in the config.yml to change the API.

**Comment by xknat** [comment]
@MinecraftKid45 we know about this issue. we are working on this. all you can do is keep updating the plugin.

**Comment by Qballl** [comment]
@xknat This is still not fixed. Are you still working on this?

**Comment by xknat** [comment]
@Qballl i am not having this issue my self. ill chek on it but @Th3Tr0LLeR is still the one who has to do it

**Comment by Qballl** [comment]
For me only a few skins work I tried using a premium skin of a previous server owner of a server I played on, on my server and I just had default skin

**Comment by xknat** [comment]
is this even still a issue? xd
