### ISSUE TITLE
Unofficial support of Thermos

### ISSUE THREAD

**Issue by ArcasCZ** [Th3Tr0LLeR/SkinsRestorer---Maro#179]
I know, you don't want to suppor Thermos, but atleast you can give us choice - warn us you can't support Thermos instead of shutting down whole plugin. As I remember, I used some version of SkinsRestorer on my Thermos server without any problems...

**Comment by ArcasCZ** [comment]
Or atleast you can highlight somewhere version 10.4.4 BETA as lats version working on Thermos...

**Comment by DoNotSpamPls** [comment]
The last version of Thermos is 1.7.10. The software itself is unsupported, we won't focus our efforts on supporting old versions of old software. Even the main plugin doesn't support 1.7.10 very well, and will likely completely lose that functionality in a few versions.
