### ISSUE TITLE
Messages messed up

### ISSUE THREAD

**Issue by AlwaysCandr** [Th3Tr0LLeR/SkinsRestorer---Maro#183]
Hello,
There is a /sr ghost message that I'm trying to remove from the config but no luck.
My messages are custom. Also I would like to know how to remove the SR_LINE option.

![screen shot 2017-02-08 at 00 12 53](https://cloud.githubusercontent.com/assets/17865871/22715971/d8b92822-ed93-11e6-8cd3-a55852e156f4.png)

The old messages were just perfect 😞 

Best Regards,
candr

_(play.majnkreft.tk)_

**Comment by xknat** [comment]
we are still working on this. please update skinrestorer
