### ISSUE TITLE
New Feature? "Tablist Skin"

### ISSUE THREAD

**Issue by xXSchrandXx** [Th3Tr0LLeR/SkinsRestorer---Maro#184]
I wonder if you can get a feature in your plugin witch displays the chosen skin in the tab list (player list in minecraft) of the server or just the dislaying of a skin in the tab list (player list in minecraft) for offline (cracked) server.

**Comment by xknat** [comment]
we did consider this way back.
the reason why we didn't do this is because we would need to import a lot of new resources / api's.
it will be so much that we could better make a new plugin with api's from skin restorer.

troller does not have such time, i am sorry.

**Comment by Th3Tr0LLeR** [comment]
https://youtu.be/Mhj15W23IjA
