### ISSUE TITLE
Players are invisible and Tab-list is broken

### ISSUE THREAD

**Issue by WolfezzKyne** [Th3Tr0LLeR/SkinsRestorer---Maro#19]
Players are invisible and Tab-list is broken on spigot 1.9

**Comment by Th3Tr0LLeR** [comment]
Can you provide some info/pictures and plugins list ?

**Comment by WolfezzKyne** [comment]
Seems only to happen with Authme-Reloaded installed, tested it

**Comment by Th3Tr0LLeR** [comment]
Yes. It's a known Authme problem. I think there was an option in the AuthMe config to fix that, but i don't know what it is.

HideTablistBeforeLogin is probably the one.

**Comment by Th3Tr0LLeR** [comment]
Authme Related.
