### ISSUE TITLE
Please, add bungee disabled option to config

### ISSUE THREAD

**Issue by InterVi** [Th3Tr0LLeR/SkinsRestorer---Maro#202]
Hi. I using proxy (not bungee), option 'bungeecord' set true. Plugin not working.It is problem. Please, add option to config, to turn off check 'bungeecord' in 'spigot.yml'.

**Comment by xknat** [comment]
Cant

**Comment by xknat** [comment]
Well we put in because you have to put skinsresotrer inside bungee if your using bungee
