### ISSUE TITLE
Plugin does not work

### ISSUE THREAD

**Issue by Xayanix** [Th3Tr0LLeR/SkinsRestorer---Maro#205]
Example output of using /skin:

https://scr.hu/0mY1mD
https://scr.hu/wXPd70
https://scr.hu/yeP5RD

Using newest version available of SkinsRestorer, BungeeCord and Spigot.
And i got spam in server log:
07:06:08 [INFO] [SkinsRestorer] Unsupported player format.. removing (michalinams).

**Comment by xknat** [comment]
for support, join our discord support server! [https://discord.me/skinsrestorer](https://discord.me/skinsrestorer)
