### ISSUE TITLE
SkinsRestorer doesn't work

### ISSUE THREAD

**Issue by InfinCZ** [Th3Tr0LLeR/SkinsRestorer---Maro#206]
I have installed SkinsRestorer on my server, and doesn't working. I many times reinstalled to and still not work. When I look to plugin list on server, plugin is in green bat doesn't show skins, I have default skin.
And so when i use command "/skin" show text "Server returned HTTP response code: 429 for URL: https://api.mojang.com/users/profiles/minecraft/InfinCZ" and my skin doesn't show.
Please help.

Thanks,
Infin

**Comment by DoNotSpamPls** [comment]
Response 429 means you have been ratelimited. This is a temporary error, and it fixes itself after 10-20 minutes

**Comment by InfinCZ** [comment]
Thanks, but still is showing.
My proxy.txt :

182.253.191.106:8080
180.250.156.186:53281
223.27.194.66:8080

**Comment by xknat** [comment]
for support, join our discord support server! [https://discord.me/skinsrestorer](https://discord.me/skinsrestorer)
