### ISSUE TITLE
SkinsRestorerAPI support for Bungeecord

### ISSUE THREAD

**Issue by Lammendam** [Th3Tr0LLeR/SkinsRestorer---Maro#208]
Hi, when i using API in my plugin on local server, it works as expected, but my live servers connected with bungeecord and SkinsRestorerAPI won't work. When I try to use
`String srSkin = SkinsRestorerAPI.getSkinName(String);`
or
`if (SkinsRestorerAPI.hasSkin(owner) == true`
it returns NullPointerException
Looks like SharedStorage has no support for bungeecord.
Maybe you implement it at your free time during writing an update?

**Comment by Cuchi28707** [comment]
Hi, I need that same feature so I hope developers of this plugin add this.

**Comment by xknat** [comment]
@DoNotSpamPls

**Comment by DoNotSpamPls** [comment]
Will do when I have time, for now it's low-priority though
