### ISSUE TITLE
[Spigot 1.12.1-R0.1] [v13.1.4] On Join, hiddens players are displayed in the tablist.

### ISSUE THREAD

**Issue by Ksehn** [Th3Tr0LLeR/SkinsRestorer---Maro#218]
Hi,

### What doesn't work (or what feature do you request)?
I use a very simple custom plugin for hidding operators on join, but, with SkinsRestorer, players are still able to see hiddens players in their tablist.

### How to reproduce the bug? (if a bug)
- Connect "Player A".
- Connect "Player B" (Hidden to everyone with **Spigot's hidePlayer method**).
- Open the tablist of Player A (Player B should be displayed).

### What version of SkinsRestorer do you use?
SkinsRestorer **13.1.4**, for Spigot.

Tell me if you need more details, or if I'm not very understandable ^-^.

Also, happy Christmas !

**Comment by xknat** [comment]
hm skinsrestorer should not effect scoreboard...

**Comment by DoNotSpamPls** [comment]
So, it goes away when you remove SkinsRestorer?

**Comment by Ksehn** [comment]
@DoNotSpamPls Yes. I will recheck everything and post more details/screens '^'.

**Comment by Ksehn** [comment]
Hi',

I've retried with this:
**CraftBukkit:** git-Spigot-da42974-8f47214 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)
**SkinsRestorer:** 13.2
**Plugins (2):** HideOnJoin, SkinsRestorer

This minor issue is still here with the latest version of SkinsRestorer.

For HideOnJoin, it's just :
```java
@EventHandler (priority = EventPriority.HIGHEST)
public void onPlayerJoinEvent(PlayerJoinEvent event) {
  if(event.getPlayer().isOp()) {
    for(Player p: Bukkit.getServer().getOnlinePlayers()) {
      if(!p.isOp()) {	
      	p.hidePlayer(event.getPlayer());
      	event.getPlayer().sendMessage("Debug: Hidden to " + p.getName());
      }
    }
  }
}
```
I'm still a newbie in Java development.

**PS:** It seems that players connecting before the operator are able to see it in their list, but, other players connecting after, can not (Except if the operator uses the / skin command).

**Comment by iskandarluqman** [comment]
I can confirm this problem is caused by SkinsRestorer. Just tried without SkinsRestorer, my name isnt visible in the tablist. At first when I test this problem, it was from AuthMe. After I did another test, I can confirm its from SkinsRestorer.
