### ISSUE TITLE
Make plugin on Async

### ISSUE THREAD

**Issue by AsVaidas** [Th3Tr0LLeR/SkinsRestorer---Maro#220]
### What doesn't work (or what feature do you request)?
Lags out on player join / player skin change

### How to reproduce the bug? (if a bug)
Make the skin put in async on playerJoin and Command events

### What version of SkinsRestorer do you use?
The newest (modified by decompiling and made the plugin on async myself)

Notes:
It's very easy and doesn't effect anything, servers get huge performance boost and timings never show something with skinsrestorer when on async. 
`Bukkit.getScheduler().runTaskAsynchronously(Bukkit.getPluginManager().getPlugin("SkinsRestorer"), () -> { CODE });`
Just place this in PlayerJoinEvent and you will help a lot of server owners

**Comment by DoNotSpamPls** [comment]
We'll be working on this, thanks for your feature suggestion!

**Comment by xknat** [comment]
yea, it has been put on our list to do for 13.3. so stay tuned and if you wish to help contact us over discord skinsrestorer support ;)

**Comment by DoNotSpamPls** [comment]
@AsVaidas you said that you made it async yourself? you could commit the code as a PR, so it can be easier for everyone 😛

**Comment by AsVaidas** [comment]
@DoNotSpamPls I deleted a lot of functions (like bungecord) because I didn't had the import list or similar, I just left the spigot part of skin change, and made command + on join event on async with 4 additional lines. The line is shown in the main comment, everything is very simple. I think I will just contact via discord and help it to be in the main plugin.
Or maybe I didin't understood the question.

**Comment by DoNotSpamPls** [comment]
This was added in the development repo, will be pushed for the next release.
