### ISSUE TITLE
[Waterfall 1.12.2]Unable to change skin while SR claims changed

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [Th3Tr0LLeR/SkinsRestorer---Maro#224]
### What doesn't work (or what feature do you request)?
As title
I believe its the fact that Waterfall changed some codes of BungeeCord that SR requires

### How to reproduce the bug? (if a bug)
https://pastebin.com/XMkMkrmQ

### What version of SkinsRestorer do you use?
13.2

**Comment by DoNotSpamPls** [comment]
We haven't really tested Waterfall, but it *should work*. By the way, are you on SkinsRestorer 13.2, or 13.3. All versions before 13.3 got broken by a Mojang API change, you can get 13.3 on our [Discord server](https://discord.me/skinsrestorer)

**Comment by Pythonic-Rainbow** [comment]
....I am using 13.2
I dun know theres an API change.Lemme test it using 13.3

**Comment by Pythonic-Rainbow** [comment]
Okie , 13.3 is the solution. Thanks!
