### ISSUE TITLE
Ideas for future versions of the plugin

### ISSUE THREAD

**Issue by DoNotSpamPls** [Th3Tr0LLeR/SkinsRestorer---Maro#226]
High priority:
- [ ] Stop getting proxies if it gets an output that's different from the expected one
- [ ] Make the config system work reliably
- [ ] Fix MySQL

Medium priority:
- [x] Be able to use your own proxies instead of GetMeProxy/MCAPI.me
- [ ] Add more languages to the plugin (French, German, etc.)
- [ ] Don't send a locale message if it's empty

Low priority:
- [ ] More permissions (such as allowing only certain skins to be used)
- [x] /sr clear
- [x] /sr status on BungeeCord
- [x] Add %skin as a variable in messages.yml
- [ ] Add a debug option that gives more insight on what causes a problem.
- [x] Don't assign a default skin if a user is premium (configurable)
- [ ] Implement HikariCP
- [ ] Replace Reflection with Abstraction

**Comment by alek-shirar** [comment]
Would very much appreciate there being working permissions in the future. Right now, regular players are allowed to change their skin.

**Comment by DoNotSpamPls** [comment]
Known bug, next version fixes it :) (although we have no ETA for the release)

**Comment by xknat** [comment]
my list: 

- [ ] way to figure out cached proxy's from a command.

**Comment by xknat** [comment]
hhmmm
