### ISSUE TITLE
1.7 support in the plugin is half-working

### ISSUE THREAD

**Issue by DoNotSpamPls** [Th3Tr0LLeR/SkinsRestorer---Maro#229]
On the protocol hack, 1.8 players can see skins, while 1.7 players can't. I suspect this is because of the format changes that 1.8 introduced.

**Comment by xknat** [comment]
Yupwe can detect server version not player version unless we add it as paid addon

**Comment by xknat** [comment]
Kuch kuch logics plugin

**Comment by DoNotSpamPls** [comment]
1.7 is not worth supporting anymore, we shouldn't need to support a **5 year** old version of Spigot.
won't fix
