### ISSUE TITLE
SkinsRestorer dont work with "Thermos-1.7.10-1448.46"

### ISSUE THREAD

**Issue by evernife** [Th3Tr0LLeR/SkinsRestorer---Maro#23]
I am having trouble with Skins Restorer, it doesn't work with Thermos.
Can You help Me?

Notes:

Used commands don't show response messages or error messages. (IN GAME)
(Only appear in the console that the player issued it)

The plugin do not appear to show any error in the console too.

**Comment by Th3Tr0LLeR** [comment]
SkinsRestorer doesn't support Thermos. Sorry.

**Comment by evernife** [comment]
Do not pretend to suport?

Cauldron stoped updating in May 13, 2015
Thermos have a better performance too :/

**Comment by Th3Tr0LLeR** [comment]
I have never supported Cauldron. I don't know if i could support Thermos.

**Comment by k1r0s** [comment]
Thermos uses Craftbukkit api, what's the issue? https://github.com/CyberdyneCC/Thermos-Bukkit/tree/ad9519650b6c3a0cf346b9a78d783221e62d99f9
