### ISSUE TITLE
Skin permissions - Bungee

### ISSUE THREAD

**Issue by AmazedMender16** [Th3Tr0LLeR/SkinsRestorer---Maro#231]
### What doesn't work (or what feature do you request)?
The permissions for the /skin command are broken. everyone has permissions to it.
### How to reproduce the bug? (if a bug)
Put skinsrestorer in your bungeecord and try the skin command with a default player
### What version of SkinsRestorer do you use?
Have tried it with latest one available on spigot. Latest one on jenkins is not working for bungeecord

**Comment by DoNotSpamPls** [comment]
Known bug, will be fixed in the next version of SR

**Comment by AmazedMender16** [comment]
Any known date for the fix? been waiting for months..

**Comment by AmazedMender16** [comment]
Placeholder "%player" is broken aswell

**Comment by xknat** [comment]
@AmazedMender16 this got fixed on another branch. kindly join our discord server and type `.iam Tester` in the chat to download the version in #srtesting
