### ISSUE TITLE
bug report: endless loop

### ISSUE THREAD

**Issue by devilib** [Th3Tr0LLeR/SkinsRestorer---Maro#235]
bungeecord version: git:BungeeCord-Bootstrap:1.12-SNAPSHOT:b5f17e7:190
SkinsRestorer version: 13.3

log:

17:32:21 [SEVERE] 	at skinsrestorer.shared.utils.ProxyManager.readURL(ProxyManager.java:67)
17:32:21 [SEVERE] 	at skinsrestorer.shared.utils.ProxyManager.updateProxies(ProxyManager.java:29)
17:32:21 [SEVERE] 	at skinsrestorer.shared.utils.ProxyManager.readURL(ProxyManager.java:67)
17:32:21 [SEVERE] 	at skinsrestorer.shared.utils.ProxyManager.updateProxies(ProxyManager.java:29)
17:32:21 [SEVERE] 	at skinsrestorer.shared.utils.ProxyManager.readURL(ProxyManager.java:67)
17:32:21 [SEVERE] 	at skinsrestorer.shared.utils.ProxyManager.updateProxies(ProxyManager.java:29)
17:32:21 [SEVERE] 	at skinsrestorer.shared.utils.ProxyManager.readURL(ProxyManager.java:67)
17:32:21 [SEVERE] 	at skinsrestorer.shared.utils.ProxyManager.updateProxies(ProxyManager.java:29)
17:32:21 [SEVERE] 	at skinsrestorer.shared.utils.ProxyManager.readURL(ProxyManager.java:67)
17:32:21 [SEVERE] 	at skinsrestorer.shared.utils.ProxyManager.updateProxies(ProxyManager.java:29)
17:32:21 [SEVERE] 	at skinsrestorer.shared.utils.ProxyManager.readURL(ProxyManager.java:67)
17:32:21 [SEVERE] 	at skinsrestorer.shared.utils.ProxyManager.updateProxies(ProxyManager.java:29)

**Comment by xknat** [comment]
join our discord for support this is not an bug ;)
