### ISSUE TITLE
Are you serious?

### ISSUE THREAD

**Issue by molor** [Th3Tr0LLeR/SkinsRestorer---Maro#236]
https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/blob/master/src/main/java/skinsrestorer/bukkit/commands/SkinCommand.java#L44

This is the only place where plugin checks for the permission to change the skin. I can take this permission away from the players, but it does not prevent them to change the skin to the one they want. Do you understand why, or I should explain more?..

I would never have thought that such a plugin can be such a mistake.
And, most interestingly, no one has yet reported it. Nobody. I'm freaking out.

By the way, will the duplication of players ever be fixed?

**Comment by McLive** [comment]
https://github.com/McLive/SkinsRestorerX Check again
