### ISSUE TITLE
[Feature Suggestion] utilization of mineskin api for signing custom skins

### ISSUE THREAD

**Issue by ITZVGcGPmO** [Th3Tr0LLeR/SkinsRestorer---Maro#237]
if SkinsRestorer utilized [mineskin](https://mineskin.org)'s api, then users could apply custom skins directly from a url instead of through an already existing username. There is [a plugin written by the developer of the mineskin api](https://github.com/InventivetalentDev/CustomSkins) which has this functionality, but it cannot sync through multiple servers on a bungeecord/waterfall proxy as this plugin can.

If this api is utilized, i highly recommend implementing a global rate limit.

**Comment by xknat** [comment]
@ITZVGcGPmO check this: https://github.com/riflowth/SkinSystem

**Comment by ITZVGcGPmO** [comment]
apparently i solved my own issue? https://github.com/SkinsRestorer/SkinsRestorerX/pull/147
