### ISSUE TITLE
Error message on join.

### ISSUE THREAD

**Issue by rErEaT** [Th3Tr0LLeR/SkinsRestorer---Maro#24]
http://pastebin.com/ZDc3imb3

I removed the skinsrestorer plugin the error disappered.
So there is an error.

**Comment by Th3Tr0LLeR** [comment]
I will attempt to fix this now.

**Comment by Th3Tr0LLeR** [comment]
@rErEaT is this happening only when MySQL is enabled or it's happening all the time ?

**Comment by rErEaT** [comment]
I never used MySQL :D

so its happening all the time

**Comment by Th3Tr0LLeR** [comment]
Unfortunately I can't fix that error, since it's spigot/bukkit related. SkinsRestorer could be causing it by sending packets, but if i stop doing that, the plugin wont work.

**Comment by rErEaT** [comment]
https://github.com/PaperMC/Paper/issues/192#issuecomment-206622182

**Comment by Jeje2201** [comment]
Oh, so this is not causing any way of crash or loosing tps ? Because I can with chatcontrol remove message who appear in the console, so I can hide this special message, if it's not causing any crash I think it's ok, I will see with the developer, thanks for the link @rErEaT !

**Comment by games647** [comment]
@Th3Tr0LLeR you could just call player.teleport(player.getLocation());

**Comment by Th3Tr0LLeR** [comment]
@games647  I believe i'm sending location packets, but yeah, i may try that.
