### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by tuanjr** [Th3Tr0LLeR/SkinsRestorer---Maro#31]
when use with mysql on Bungeecord
01:43:50 [INFO] [SkinsRestorer] Connected to MySQL!
01:43:51 [INFO] [SkinsRestorer] MySQL error: Multiple primary key defined

**Comment by Blackfire62** [comment]
Its an error which only occurs on the server start (checking tables) .
It shouldnt affect the functions of the plugin in any way, so dont worry.
