### ISSUE TITLE
[Enhancement] Heads in tablist

### ISSUE THREAD

**Issue by Platinteufel** [Th3Tr0LLeR/SkinsRestorer---Maro#34]
Do you know if it's possible to show the heads of the skins set by SkinsRestorer in tablist? :)

**Comment by Blackfire62** [comment]
Heads in tab are client sided, and are bound to connection to mojang servers via online mode .
In short, warez players cant see these, but premium players that will use online mode can.

**Comment by Platinteufel** [comment]
hm okay, thank you tho :)
