### ISSUE TITLE
skinrestorer

### ISSUE THREAD

**Issue by 0211cgo2000** [Th3Tr0LLeR/SkinsRestorer---Maro#37]
when i use that skin.It work but when i use command /skin set or /set skin i forgot but it say you dont have permission to execute this command.Pls i need help!!!

**Comment by Th3Tr0LLeR** [comment]
You should add the required permissions..

**Comment by 0211cgo2000** [comment]
how
i have add - skinsrestorer.cmds
                - skinsrestorer.playercmds
                - skinsrestorer.bypasscooldown
                - skinsrestorer.disabledskins
