### ISSUE TITLE
Skin wont save with Premium name

### ISSUE THREAD

**Issue by tuanjr** [Th3Tr0LLeR/SkinsRestorer---Maro#39]
I'm current running offline-mode server, 1.9.2 with SkinsRestorer lastest version, and have issue is player with premium name when they use skinsrestorer, their skin wont save, after logout, skin reset to default premium skin.
With name is not Premium name, everythings work fine.

**Comment by baticag** [comment]
I have the same problem on my server, but I am running 1.8.9 latest

**Comment by Mabus13** [comment]
same problem spigot 1.9.2

**Comment by Th3Tr0LLeR** [comment]
I will look into that.

**Comment by Th3Tr0LLeR** [comment]
I just tested now with 1.8 to 1.9.2 and it worked fine. The skin is deleted from the cache only if the timestamp is too old. Are you using MySQL or the yml storage ? I tested with the YML storage.

**Comment by tuanjr** [comment]
same problem on both mysql and file file storage. Skin plugin run under bungeecord, are you test with bungeecord version? and when bungeecord restart?

**Comment by Mabus13** [comment]
I use mysql. For test need time, maybe hour or maybe more. But it few times per day. And very onoying players.

**Comment by Mabus13** [comment]
Maybe beter save name seted skin, not only cache. And when cache do update, use for updating name seted skin what was saved.

**Comment by Th3Tr0LLeR** [comment]
Yeah. Didn't test on bungeecord.

**Comment by Th3Tr0LLeR** [comment]
Tested with bungeecord. Working without any problem. YOu should stop it with /end, not directly.

**Comment by tuanjr** [comment]
yes, i stop bungee with /end command. What is directly? how to?

**Comment by Mabus13** [comment]
Th3Tr0LLeR, problem real exist, because i noticed about this by few players. =(

**Comment by tuanjr** [comment]
me too, many months ago.

**Comment by Mabus13** [comment]
Hmmm, my problem fresh, after update to version 11.4 Before player skin saved fine.

**Comment by Th3Tr0LLeR** [comment]
Still working fone for me....

**Comment by Th3Tr0LLeR** [comment]
Shouldd be fixed.
