### ISSUE TITLE
Add from URL skin

### ISSUE THREAD

**Issue by KareemMAX** [Th3Tr0LLeR/SkinsRestorer---Maro#4]
Sometimes someone want to change his skin to a skin from url which he made
please add the feature

**Comment by Th3Tr0LLeR** [comment]
I can't do this atm :/

**Comment by KareemMAX** [comment]
I think you can because you are changing the skin URL holder

**Comment by Th3Tr0LLeR** [comment]
To change the skin i need a valid signature which i don't have if i try to change the skin from an URL.

**Comment by KareemMAX** [comment]
Ok :(
What about ProtocolLib?

**Comment by Th3Tr0LLeR** [comment]
I don't want to use ProtocolLib.

**Comment by KareemMAX** [comment]
But maybe ProtocolLib have the ability to change the skin using the URL
You can also add the source code of the ProtocolLib classes that you use in your plugin
It's open source :)

**Comment by Th3Tr0LLeR** [comment]
I don't want to use ProtocolLib in SkinsRestorer

**Comment by KareemMAX** [comment]
As you like
