### ISSUE TITLE
Premium skins don't auto update

### ISSUE THREAD

**Issue by baticag** [Th3Tr0LLeR/SkinsRestorer---Maro#40]
Greetings,

I have a problem with SkinsRestorer since you added BukkitModule. When premium player joins the first time he gets his skin, but when after some time he changes skin on Minecraft.net it isn't updated on server at all. It only updates if I do command for drop or update.

Can you please look into this?

Thanks in advance!

**Comment by Th3Tr0LLeR** [comment]
Yeah. I will look into that when i have free time. Thanks.

**Comment by baticag** [comment]
Can you please look into this? It's urgent. Thanks

**Comment by Th3Tr0LLeR** [comment]
They aren't supposed to auto update. If they do, then the cache is useless. The skin is removed from the cache after some time and then, the new skin should be applied.

**Comment by baticag** [comment]
And that time is when? Because I waited for 2 days to see if they update and nothing happened!

**Comment by Th3Tr0LLeR** [comment]
Just drop the data on each login if you want, but since other server doesn't want it i wont do it for the official release.

**Comment by baticag** [comment]
Okay let's think for a moment. I don't think that dropping data on login is the solution, because I see this as a problem which started happening after you added BukkitModule. Since I am using BungeeCord latest version and latest version of your plugin, can you look if there is a problem when skin updates automaticly it is not sent from Bungee to BukkitModule? I am really trying to solve this and I will try to help you as much as I can to test it out, because it is crucial for my server. Thanks!

**Comment by Th3Tr0LLeR** [comment]
Yeah. I will think about that and see what i missed from the old versions.

**Comment by baticag** [comment]
Any news?

**Comment by Th3Tr0LLeR** [comment]
Should be fixed.
