### ISSUE TITLE
Spigot 1.8.8

### ISSUE THREAD

**Issue by NelsonHD** [Th3Tr0LLeR/SkinsRestorer---Maro#42]
/sr set myid myid
then it will "§4Skin fetch failed: §cAn error has occured: java.lang.NullPointerException: null" and can't show any skin.

Lastest BungeeCord, Java 8 64 bit and offline server.

Also, will have a update for "https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/issues/33" this issue ?
Thx

**Comment by Th3Tr0LLeR** [comment]
I closed it, since it should be fixed. About that it's because mcapi.ca

**Comment by NelsonHD** [comment]
So,how can i solve it ?

Th3Tr0LLeR <notifications@github.com> 於 2016年4月18日星期一 寫道：

**Comment by Th3Tr0LLeR** [comment]
You can't

**Comment by NelsonHD** [comment]
What should i do now

Th3Tr0LLeR <notifications@github.com> 於 2016年4月18日星期一 寫道：

**Comment by Th3Tr0LLeR** [comment]
YOu can't really do anything about this issue.
