### ISSUE TITLE
Suggestion: Sponge Port

### ISSUE THREAD

**Issue by GershonR** [Th3Tr0LLeR/SkinsRestorer---Maro#43]
Hi, I would really like to use this plugin if it would be ported to Sponge.

Thank you

**Comment by Th3Tr0LLeR** [comment]
Some time ago a DEV made forge version of SkinsRestorer, but it was long time ago and i've lost it. About Sponge support. I can't really do that.

**Comment by GershonR** [comment]
If you could find the forge version that would be great since Sponge supports forge mods

**Comment by Blackfire62** [comment]
I didnt really look into sponge nor forge, but I may do so if there will be more requests.

**Comment by Th3Tr0LLeR** [comment]
I will close that since i wont do it. Sorry.
