### ISSUE TITLE
Bungeecord not working :( 

### ISSUE THREAD

**Issue by Skin0x** [Th3Tr0LLeR/SkinsRestorer---Maro#44]
Hello,

I'm trying to use SR on my BungeeCord network, but no way ! =[ 
No errors in the logs.

**Bungeecord version:** git:BungeeCord-Bootstrap:1.9-SNAPSHOT:b6b015f:1142 by md_5 (
**Plugin's loading on Bungee:** http://puu.sh/op7Mu/8d419149fa.png

**Spigot version:** PaperSpigot-6c710c1-ba32592 (MC: 1.8.3) || Already tried with the latest version
**Skin restorer version:** SkinsRestorer-v11.4

**In game Screen:** http://puu.sh/op86C/c3761f0cfd.jpg

I have also Skype if you want, and I can ensure you that I will donate you if you can help me to solve this problem in emergency.
My skype: web-prod.khalil

Skin0x

**Comment by Skin0x** [comment]
Hello, I FIXED IT ! =D

It was a small problem of SSL certificates.
The skins were not downloaded ^^

**For persons who'll have a similar problem on debian or ubuntu, use this command:**
`sudo /var/lib/dpkg/info/ca-certificates-java.postinst configure`

Good bye =)

Skin0x

**Comment by Th3Tr0LLeR** [comment]
@Skin0x What was the error on the chat if you try /skin set ? 
handshake exception or null ?

**Comment by Skin0x** [comment]
Nothing It was not a MC Server problem but It was a problem with my SSL Certificate (Debian), so a network problem with the dedicated server ^^
