### ISSUE TITLE
SkinsRestorer not working

### ISSUE THREAD

**Issue by PONYFOX** [Th3Tr0LLeR/SkinsRestorer---Maro#45]
Hello, i've tried to install SkinsRestorer on my server but it not initializing properly. Here's the error report: http://zerobin.lgear.fr/?f0971c986b52adb0#nV9bGIlRqahDnRMYlIZQdIlmT4g8ycuZ/LY4y/aEgPk=

Any idea?

**Comment by Th3Tr0LLeR** [comment]
Try to re-download.

**Comment by PONYFOX** [comment]
It's not working too, with an older version too

**Comment by Th3Tr0LLeR** [comment]
I don't see what's wrong with my code. You should check if it will work with another spigot version.

**Comment by Bodyash** [comment]
Latest spigot. Cant understand, its skinsrestorer or mcapi not working :c
![default](https://cloud.githubusercontent.com/assets/2454569/14779952/36278eb6-0ae3-11e6-97e2-46b467f19ee1.PNG)

**Comment by Bodyash** [comment]
Yeap, doent work. Removed SkinsRestorer folder, updated Spigot, nothing.

**Comment by CrazyPHP** [comment]
Not working, confirm!

**Comment by PONYFOX** [comment]
Allways an error with others versions of SR an Spigot

**Comment by Th3Tr0LLeR** [comment]
This is not happening with most of the people...

**Comment by Bodyash** [comment]
Rly? Old versions work PERFECTLY.

**Comment by Th3Tr0LLeR** [comment]
Fixed. Try v11.5.2
