### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Bodyash** [Th3Tr0LLeR/SkinsRestorer---Maro#46]
![image](https://cloud.githubusercontent.com/assets/2454569/14764098/5c07e016-09b4-11e6-8ac2-c5ad332232ee.png)

**Comment by Bodyash** [comment]
While any player log in - i get this error.
Also i doesnt have skin now.
Removed /plugins/SkinsRestorer folder.
I have licence account C:

![2016-04-24_00 35 41](https://cloud.githubusercontent.com/assets/2454569/14764110/95d81162-09b4-11e6-8e19-c2b404bec15e.png)

**Comment by Bodyash** [comment]
Hmmm, its mojangs servers down. But error still appears.

**Comment by Th3Tr0LLeR** [comment]
I will check the error out.

**Comment by Bodyash** [comment]
![default](https://cloud.githubusercontent.com/assets/2454569/14771283/30b0940e-0a8f-11e6-8096-fc779594c48b.PNG)
Latest version. Just for report

**Comment by Th3Tr0LLeR** [comment]
Fixed
