### ISSUE TITLE
No skins --- problem is now FIXED

### ISSUE THREAD

**Issue by dunaland1** [Th3Tr0LLeR/SkinsRestorer---Maro#47]
Skins Restorer has stopped working. I don't recall changing anything. Commands work, no errors in console or chat but skin reamins the same - default one. Latest spigot and latest SkinsRestorer

**Comment by dunaland1** [comment]
Also there is a typo in your spigot page. Bottom last sentance says:  Do report issues/problems in the reviews tab. I guess it should be Don't

**Comment by xion87** [comment]
+1 same issue, rolling back to 1.14

**Comment by CrazyPHP** [comment]
same, it worked for few hours but then all skins turned into default steve!

**Comment by BiggCheePod** [comment]
Same, It worked perfect but today all skins are gone idk why

**Comment by BiggCheePod** [comment]
Please fix this hurry

**Comment by xion87** [comment]
@BiggCheePod Just use 1.14 version

**Comment by BiggCheePod** [comment]
Well 1.14 version didn't worked for me but v11.0-v2 worked

**Comment by CrazyPHP** [comment]
it's true, v11.0-v2 is work!

**Comment by ntgh-dimako** [comment]
V11.3 is last working

**Comment by xion87** [comment]
same here

**Comment by DragonbornCommunity** [comment]
same here

**Comment by AmazedMender16** [comment]
Same here, no skins in my entire server :(

**Comment by Augustin37** [comment]
Same, V11.0-V2 is working great (I tried V11.3, but /skinsrestorer drop makes an error for me)

**Comment by dunaland1** [comment]
We all know it's fixed now so I am closing this.
