### ISSUE TITLE
skins does not update automatically

### ISSUE THREAD

**Issue by simux98** [Th3Tr0LLeR/SkinsRestorer---Maro#49]
Premium accounts (skins) does not update automatically, also using /skin set, it does not do anything.

I'm using latest version of 11.5.1

**Comment by Skin0x** [comment]
Same problem ! ='( Yesterday it was working :x:

**Comment by Skin0x** [comment]
@simux98 Use v11.3 it's the last who work :+1:

**Comment by simux98** [comment]
@Skin0x Thanks, it worked :+1:

**Comment by Th3Tr0LLeR** [comment]
Fixed. Try v11.5.2 www.skinsrestorer.net
