### ISSUE TITLE
SkinsRestorer-v11.5.1 & MCAPI error

### ISSUE THREAD

**Issue by Airnexus** [Th3Tr0LLeR/SkinsRestorer---Maro#50]
/skin set <player>
->
`Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@77102b91, id=15, owner=skinsrestorer.bungee.SkinsRestorer@9ebe38b, task=skinsrestorer.bungee.commands.PlayerCommands$1@68559095, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException
	at skinsrestorer.shared.utils.DataFiles.getLong(DataFiles.java:162)
	at skinsrestorer.shared.storage.SkinStorage.getSkinData(SkinStorage.java:160)
	at skinsrestorer.bungee.commands.PlayerCommands$1.run(PlayerCommands.java:113)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)`

/sr set <player> <player>
->
§4Skin fetch failed: §cAn error has occured: java.lang.NullPointerException: null

Here is my config
`##############################################
#           SkinsRestorer Config             #
#            Made By Th3Tr0LLeR              #
##############################################

#Should SkinsRestorer check for updates ?
Update Check: true

#You can enable that if you're using AutoIn.
Use AutoIn Skins: false

#This can be enabled if you are experiencing bot attacks.
Use Bot Feature: false

#This is for preventing skin change spam.
Skin Change Cooldown: 30

#Mojang has a limit for getting skins.
#This website uses proxies to get the skin data
#From mojang, so you will not be limited.
#However. If you do not trust mcapi.ca, you can disable that option.
MCAPI:
  Enabled: true
  Get Profile URL: https://mcapi.ca/SR/?player\u003d{username}
  Get SkinProfile URL: https://mcapi.ca/name/uuid/{uuid}

#A list of disabled skins. A permision will be needed for them.
Disabled Skins:
- SomeSkin
- AnotherSkin

#If this is enabled and configured SkinsRestorer will keep the skins
#in a MySQL database. This is using less performance.
MySQL:
  Enabled: false
  Host: localhost
  Port: 3306
  Database: db
  Table: Skins
  Username: root
  Password: pass

#Turn this to true if you want to disable
#The /skin command.
Disable Skin Command: false`

**Comment by Th3Tr0LLeR** [comment]
Java 6 for the win :D

**Comment by Airnexus** [comment]
So, i should install Java 6 to solve it ?

**Comment by nicuch** [comment]
Use SkisRestorer v11.3

**Comment by Airnexus** [comment]
but v11.3 can't connect to MCAPI and i need that MCAPI

**Comment by Airnexus** [comment]
since "Skin fetch failed: Rate limited"

**Comment by Th3Tr0LLeR** [comment]
Try v11.5.2 www.skinsrestorer.net

**Comment by Airnexus** [comment]
v11.5.2 still same issue

**Comment by Th3Tr0LLeR** [comment]
It's caused by mcapi.ca. The owner of the website is working on a fix. It's not caused by SkinsRestorer.
