### ISSUE TITLE
Spigot 1.8.8

### ISSUE THREAD

**Issue by NelsonHD** [Th3Tr0LLeR/SkinsRestorer---Maro#56]
My server : 
- spigot-1.8.8-R0.1-SNAPSHOT-latest ( today download )
- BungeeCord-latest ( today download )
- Java 8
- Offline Server and offline bungeecord
- location: TaiWan

When i type : `/sr set nelson nelson` and `/skin set nelson`
My minecraft will show : `§4Skin fetch failed: §cAn error has occured: java.lang.NullPointerException: null` and can't see any player's skin.

I putted SkinsRestorer.jar into my BungeeCord's plugin folder. Also, I putted SkinsBukkitModule.jar into the plugins of all servers.

![image](https://cloud.githubusercontent.com/assets/15835385/14953221/066b2f90-109a-11e6-8bd9-f7aa45855109.png)

**Comment by NelsonHD** [comment]
and would you give me your 1.8.8 lastest bungeecord.jar and spigot for me to test it again ? Thz

**Comment by Th3Tr0LLeR** [comment]
Should be fixed in the next push.
