### ISSUE TITLE
Error, can't find premium player

### ISSUE THREAD

**Issue by Eredrim** [Th3Tr0LLeR/SkinsRestorer---Maro#58]
Hello,

I have a problem. Yesterday I reinstall the plugin in its last version. The plugin worked (7 players get their skin) perfectly but today, it doesn't work anymore.

The error I have when I type /pa set <pseudo> <skin_pseudo> is `Skin Fetch Failed. Can't find a valid premium player name`. I tried with real premium accounts names.

**Comment by xion87** [comment]
same thing here, maybe is related to minecraft site change? https://minecraft.net/it/

**Comment by CrazyPHP** [comment]
Confirm, same error.

**Comment by Deku** [comment]
Confirm, same error on spigot 1.9.2
