### ISSUE TITLE
Not all skin are working

### ISSUE THREAD

**Issue by belfedia** [Th3Tr0LLeR/SkinsRestorer---Maro#60]
With 11.3 all skin working well on my server (paperspigot #712 // Waterfall #199)
With 11.6 only some skins working, some not.

Like try /skin set gubbson with 11.3 / and 11.6

I think some minecraft account don't have update skin with new layer (player no more playing)
Your old sofware 11.3 is working with this kind of skin, but not 11.6

**Comment by Bodyash** [comment]
jokich ant kit_kat321 too
