### ISSUE TITLE
skin set not work at all

### ISSUE THREAD

**Issue by CrazyPHP** [Th3Tr0LLeR/SkinsRestorer---Maro#62]
Hello.
Skin set on v. 11.6 not work at all, and no errors given. I tried it with mcapi and without it, all variants not work!

Spigot 1.9

**Comment by Blackfire62** [comment]
Enable debug and pase the created file.

**Comment by CrazyPHP** [comment]
debug.txt paste: http://paste.ofcode.org/AdbJvp9AVU2Nn6ZBNHAqe3
cache.yml paste: http://paste.ofcode.org/uQiCYjdXmebmwTXGge7Ay2

When i login to server i see my real skin, but when i type **/skin set Mzilla** (or any other name) i get default steve skin. Both for mcapi and mojang api.

No errors in server log.

**Comment by Blackfire62** [comment]
Thats because MZilla actually has a steve skin.

Debug seems legit. Try other nicknames, when you get skin on login, there is no reason for not getting skin  on command.
