### ISSUE TITLE
Problem with skins

### ISSUE THREAD

**Issue by EnDoSiA** [Th3Tr0LLeR/SkinsRestorer---Maro#63]
I dont know why but why warez players see different skins how premium players ? And why skin not saving... Every time when i logged to my server i must again set skin.... Older version work fine on my 1.8.9 server but latest version on 1.9.2 terrible.... please fix this problems thanks

**Comment by Th3Tr0LLeR** [comment]
Depends on how much time it takes you to rejoin. The skins are removed from the cache at a time.

**Comment by EnDoSiA** [comment]
And what about my first question ? Why players see different skins, for example:
I have premium account with skin but i change skin and warez players see default premium skin but premium players see changed skin 
Why is that?

**Comment by xion87** [comment]
same issue, skin are not saved, i setted a skin to a my friends and he lost it after some hours

**Comment by Th3Tr0LLeR** [comment]
I fixed the skin cache expiring. It's normal for the skins to expire. the /skin set command is not for official use...

**Comment by xion87** [comment]
so which command is "official" now? o.o

**Comment by Th3Tr0LLeR** [comment]
It's SkinsRestorer, not skinchanger.
It was supposed to restore skins on cracked servers. Remember that ?
