### ISSUE TITLE
MySQL - some skins are stored incorrectly

### ISSUE THREAD

**Issue by FreeWall** [Th3Tr0LLeR/SkinsRestorer---Maro#64]
Using latest build SkinsRestorer 11.6 and spigot 1.9.2.

Some of the skins in MySQL are stored incorrectly.
In "Value" column there should be base64 encoded json data of skin, but not always there is just base64.

Example of wrong stored skin (Value column) (end of line): `eyJ0aW1lc3RhbXAiOjE0NjI4MDI3ODAzMjcsInByb2ZpbGVJZCI6IjZiM2NjMDRjNmQ2ODQ4MWNhZmJmNjZkNDFiMDQ3YjA5IiwicHJvZmlsZU5hbWUiOiJha2FmbHVmZnkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnt9fQ=="}],"legacy":true`

Sometimes, there is not base64 format at all in Value column and there is just json format:
`{"uuid":"468786988ce34a6989812a2370a4e648","uuid_formatted":"46878698-8ce3-4a69-8981-2a2370a4e648","name":"Darius","properties":[{"signature":"b57wArFojArflnV915y\/5RFruJM1YTEEMfgQWqTzZA0+x\/xAoI1xdajY93qe8cM+6Sw+zl+5i1fsXPfRwaWJZq1ghTlfRpU+uVAoYTwwt0n\/mUsKm5W7oYAuiBSZSLSSIvA\/wMnCuxnlfJxjVCJJcRCFCi6keT1+pZUHURfZABp8NkMMjvGowWsEoL9AYdsNxulyzmdpEz5zVmjL5rJFBEz\/waczS5z+EC\/giHWfm51AxOK5kyS39D4W1PZYP8Fk0NjyiG4BXN0eBEYNqPzyj0rjUghtvGBRL\/mISaS69lr55ro\/Odi5gzxSlBU5wQdguJQUkAVUJ3+Z6o8grT10fsxLoO9dep6zDUrSWAcd9SO5jm3CtgpilW6f49XWun3rbonVnzp1qoiBAsOFIas\/vCLoVL5SV41OwcnGX7ngMrhmy97quF6huvwH\/IvLIJJyrwsAugJ8\/BlfHXafNUwvuFYcX\/WX+Eb4IdB6pKzKRwHEQhhThbYA3cLluy9XArhXpGMe7qtk9V+dhagDL5\/i4+mgXh3SD0YQUdw6I+KJky7drxsu1V242V2Ukb6qxLXcsnwpwdBryJy0eRixJxtnuhGbctxewXc7UjrKnwM84zUgfhKR9jfkn1H\/4JcOQs3FeeHzzJ7xCwt6BHG0rFj3Vs3PxUr6nrOdRi5p+J1q5Kw=","name":"textures","value":"eyJ0aW1lc3RhbXAiOjE0NjI3MzA4NjQ5MTAsInByb2ZpbGVJZCI6IjQ2ODc4Njk4OGNlMzRhNjk4OTgxMmEyMzcwYTRlNjQ4IiwicHJvZmlsZU5hbWUiOiJEYXJpdXMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzdkN2IxMzUxZWFiMWMzOTJmODVmZTZlNDUyMWQzNmFjMTY2OWE1N2EyNjFjYTYxNzNmNTllNThkNGYyOTFmMzgifX19"}],"properties_decoded":[{"timestamp":1462730864910,"profileId":"468786988ce34a6989812a2370a4e648","profileName":"Darius","textures":{"SKIN":{"url":"http:\/\/textures.minecraft.net\/texture\/7d7b1351eab1c392f85fe6e4521d36ac1669a57a261ca6173f59e58d4f291f38"},"CAPE":{"url":null}}}],"cache":1462734285,"cache_length":"00:57:00","proxy_number":"10"`

I manually read from this DB to get some skin information for my plugin and these issues bothers me, thank's for your reply.

Sorry for my bad english.

**Comment by Blackfire62** [comment]
Its nice that you know what a base64 string is, but you forgot the debug.txt file. 

Skin data are only sent to db incorrcetly if they are read incorrectly.
And if so, we could see that from debug file.

**Comment by FreeWall** [comment]
I don't have debug.txt file now, because i had to restart my bungee network,
but I would suggest to not saving skin to DB if the skin is read incorrectly, or is that a standard behavior?

**Comment by Blackfire62** [comment]
Then get it as soon as possible.

Uh, I guess?
Ever since in my testing i didnt experience incorrect read of the skin data, there is no filter for that.
When ill see the output of debug.txt (how are things read and saved) i can make a new filter pattern (in case MojangAPI is unstable because why would it respond in different way every time, right? )

**Comment by FreeWall** [comment]
I don't know why is that happening, I just reported a obvious bug and trying to help with a development. I can deal with it on my own just by adding some filters.

I will try to send debug.txt tomorrow.

**Comment by FreeWall** [comment]
OK, there is debug.txt file, finally :-).
[debug.txt](https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/files/255790/debug.txt)

**Comment by Blackfire62** [comment]
As you might have noticed, debug is clean, all the string look fine.

There is no way something deformed like you posted could get sent to db. It would have to be read from raw string wrongly (which it isnt if you look at the structure of Notch example in debug file ). Also the skin would not work (bc the string would be deformed) and then it would get sent to DB .

**Comment by FreeWall** [comment]
Well, it's obvious there is a way because it is happening. I don't know how debug.txt works, because server is running about 12 hours and there were about 12 skins in DB stored incorrectly but debug.txt is the same. Never mind, I will fix this bug on my own.
