### ISSUE TITLE
Some player can't login because skinsrestorer

### ISSUE THREAD

**Issue by xion87** [Th3Tr0LLeR/SkinsRestorer---Maro#66]
Hi i just noticed the error that i reported on viaversion is definitly caused by skinsrestorer and not other plugin, removing skinsrestorer it solve all issue. plugin is installed on bungee side and when a player try to login it output this error on bungee console http://pastebin.com/3diJM3St

**Comment by xion87** [comment]
i got dupe values in cache.... for the player that crashed...

**Comment by Th3Tr0LLeR** [comment]
Mojang are always changing the way that stuff works. They rly wanna prevent that.

**Comment by xion87** [comment]
was a fault of older version... i just reseted cache and now work fine

**Comment by xion87** [comment]
consider it fixed it was a issue with old versions
