### ISSUE TITLE
Problem with  essentials.joinfullserver and the server is full

### ISSUE THREAD

**Issue by ashitoman** [Th3Tr0LLeR/SkinsRestorer---Maro#67]
the player loses his skin when joins with essentials.joinfullserver permission and the server is full

spigot 1.9.2

**Comment by Blackfire62** [comment]
No way this can happen, the plugin does not even care about anything slot, player count or essentials related.

Also what do you mean by "lose skin" ? Its not visible? Does he have it in db? 

Provide more info, also debug justin case.

**Comment by Th3Tr0LLeR** [comment]
Should i now make a pic on your 3 posts ? :D

2016-05-13 23:03 GMT+03:00 Blackfire62 <notifications@github.com>:

**Comment by ashitoman** [comment]
I'll make a little video later

***"Also what do you mean by "lose skin" ? Its not visible? Does he have it in db? "

When the player joins when the server is full(Staff and vips) he looks like steve
example:
max players = 1 (in server.properties)
then
redhot joins, he have the skin "stormtropper" (normaly)
then 
another user no premium "ashitoman"(staff) (before he used /skin set wesker) joins in the server and his skin is steve

sorry my bad english
