### ISSUE TITLE
Skins sometimes not work latest versions

### ISSUE THREAD

**Issue by andris155** [Th3Tr0LLeR/SkinsRestorer---Maro#71]
SkinsRestorer 10.3 - works always.
SkinsRestorer latest versions - skin sometimes not work.

Uses:
Waterfall(SkinsRestorer) + Paper 1.9.4(SkinsBukkitModule)

Config:
Update Check: false
Use Bot Feature: true
Skin Change Cooldown: 60
MCAPI:
  Enabled: true
  Get Profile URL: https://mcapi.ca/SR/?player\u003d{username}
  Get SkinProfile URL: https://mcapi.ca/name/uuid/{uuid}
MySQL:
  Enabled: true
Disabled Skins:
- SomeSkin
- AnotherSkin

Disable Skin Command: false
Debug Enabled: false

**Comment by xion87** [comment]
i noticed also that, account that are still not migrated to mojang dont work

**Comment by Augustin37** [comment]
I have the same problem, some skins do not work like "KingTramp" for example

**Comment by andris155** [comment]
fixed
