### ISSUE TITLE
Skinsrestorer make some player to crash random

### ISSUE THREAD

**Issue by xion87** [Th3Tr0LLeR/SkinsRestorer---Maro#72]
http://hastebin.com/yugiwopuji.coffee
i got skinrestorer installed on bungee side, and randomy after some hours (5-6) it make all player to crash with these errors, btw is not a viaversion issue, i already tried without it and i got  same issue (viaversion just complain about bad packets)
all is reported well here https://github.com/MylesIsCool/ViaVersion/issues/384

hope that it will be fixed soon...

**Comment by xion87** [comment]
found some snip errors on bungee side, notice the error java.lang.NullPointerException is spammed on spigot servers instead
http://hastebin.com/oxifabofuc.coffee

**Comment by xion87** [comment]
Massive error spam that make all user on my hub crash
http://hastebin.com/ifevegipoj.avrasm

**Comment by Th3Tr0LLeR** [comment]
The plugins are incompatible.

**Comment by xion87** [comment]
@Th3Tr0LLeR  which ones?....

**Comment by xknat** [comment]
GL

**Comment by xion87** [comment]
Bungeee plugins or spigot plugins?

**Comment by Th3Tr0LLeR** [comment]
U know it's incompatible with viaversion...

**Comment by xion87** [comment]
i told that i tested it without using viaversion, i got the same issue... please read here https://github.com/MylesIsCool/ViaVersion/issues/384 , viaversion just trigger some error that skinsrestorer is doing
