### ISSUE TITLE
Skins Reset On Reconnect

### ISSUE THREAD

**Issue by TheNoiseZA** [Th3Tr0LLeR/SkinsRestorer---Maro#73]
Hi TheTroller,

I have been having an issue with v11.6.1 as follows:
Non premium user connects with premium name, sets skin, no problem.
When the user reconnects, the skin is set to the default of the premium account.

Premium user connects, sets skin, no problem.
Reconnect, no problem.

Using protocollib 4.0, spigot 1.9.4 latest build.

Thanking you
Noise

**Comment by Platinteufel** [comment]
#69
I'm also waiting for a fix. :/

**Comment by Bodyash** [comment]
+, too much time without any updates at spigotmc

**Comment by Th3Tr0LLeR** [comment]
No time at all.

**Comment by Blackfire62** [comment]
Fixed in next version
