### ISSUE TITLE
Point of using a database

### ISSUE THREAD

**Issue by l33t0r** [Th3Tr0LLeR/SkinsRestorer---Maro#74]
Hi all,

I'd like to know what exactly the point of the database is?
I've connected a MySQL database to the plugin. I thought that this would "save" the skin for that specific user, so that in case the plugin would break again, the skin would be loaded from the database.

But I assume this is not what it's used for, because skins stopped working again a few days ago, while the database still holds all the data for the skins set before it stopped working.
So, what is it really used for?

**Comment by Blackfire62** [comment]
Saving skin data, obviously, its no different from local storage except for that its useful for multi bungee servers and others.

Also "skins stopped working" is not considered enough information about your problem.

**Comment by l33t0r** [comment]
Well, that's my point. It should store the skins, but it does not.
You'd think that when it fails to fetch the skins from the servers, it should fetch them from the database.
But since I was not sure that this was actually what the database is for, I figured I should ask first.
According to the server's startup logs, the connection to the database works fine, and I can confirm that data is stored in it. What other information can help us find the issue?

The reason I didn't elaborate on the "stopped working", it because I want to open a new ticket for that later. What information would be useful when I post that?
