### ISSUE TITLE
SkinsRestorer netty crash.

### ISSUE THREAD

**Issue by Dimatert9** [Th3Tr0LLeR/SkinsRestorer---Maro#75]
https://github.com/MylesIsCool/ViaVersion/issues/411
https://hub.spigotmc.org/jira/browse/SPIGOT-2309
http://pastebin.com/wsVWVG46

without skinsrestorer all good.

**Comment by Dimatert9** [comment]
i found why.
This player DB when crash: http://pastebin.com/kxfPqdrJ
This when i dont have crash: http://pastebin.com/eqbkDt9z
Player dont have value and timestamp in DB.

**Comment by Dimatert9** [comment]
https://youtu.be/k72mmqpq9Yo

**Comment by xion87** [comment]
it cause like all players to crash after some hours?

**Comment by Dimatert9** [comment]
Yes. When player join, all players was kicked.
https://github.com/WaterfallMC/Waterfall-Old/issues/76

**Comment by xion87** [comment]
more corrupted player on database
http://hastebin.com/liqidatima

**Comment by Dimatert9** [comment]
http://pastebin.com/wd4mBCFs
http://pastebin.com/k0U9R7cS
