### ISSUE TITLE
Not working since 1 week (spam mojang api)

### ISSUE THREAD

**Issue by ashitoman** [Th3Tr0LLeR/SkinsRestorer---Maro#82]
Hi, when I try to change the skin just don't work
and shows this
![errorr](https://cloud.githubusercontent.com/assets/19341044/15701713/9b0bc5f6-27a1-11e6-959c-a091299973fc.png)
I'm trying skin set notch, skin set GioYT (premium accounts)
![error2](https://cloud.githubusercontent.com/assets/19341044/15701792/10223596-27a2-11e6-881d-c498dcf04428.png)

Plugin version
SkinsRestorer 11.6.1

Server Versión
![version](https://cloud.githubusercontent.com/assets/19341044/15701845/4245c042-27a2-11e6-8f0a-b3c3723f5bf5.png)

PS: When I use /skull that give me a skull without texture,
the support of the host tells me:
![spam](https://cloud.githubusercontent.com/assets/19341044/15701881/7370d210-27a2-11e6-8238-2f5f3401ec95.png)

Skull
![skull](https://cloud.githubusercontent.com/assets/19341044/15701893/8e81de3c-27a2-11e6-9508-23fa096cfb08.png)

the plugin config is the default

What's wrong?

**Comment by Blackfire62** [comment]
Update to latest version and check your IPtables if youre using dedicated server.

Also ill make new update very soon, you shouldnt have any of these problems later on.

**Comment by Bodyash** [comment]
Where i can download latest version?

**Comment by ashitoman** [comment]
That's the why in my server no body can use skins and /skull ?
what about mcapi.ca  ? is really working in your plugin?

I have 50/50 players in my server
now I'm blocked from mojang
![sin titulo](https://cloud.githubusercontent.com/assets/19341044/15752306/2d6c4026-28b3-11e6-959c-033e7e12bd9a.png)

**Comment by Blackfire62** [comment]
Skull skins are acquired different way that player skins, I doubt it has something to do with it.

**Comment by ashitoman** [comment]
Blackfire62
I'm rated limited maybe by your plugin 
![error](https://cloud.githubusercontent.com/assets/19341044/16220208/eb898c52-3750-11e6-9986-210ec13ce2a9.png)
