### ISSUE TITLE
Craftbukkit

### ISSUE THREAD

**Issue by TryHardDood** [Th3Tr0LLeR/SkinsRestorer---Maro#84]
In craftbukkit we don't have `net.md_5.bungee.api.ChatColor`, `net.md_5.bungee.api.plugin.Plugin` and `net.md_5.bungee.api.ProxyServer` classes so the plugin throws errors. ( https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/search?q=md_5 )

**Comment by Blackfire62** [comment]
Why does anyone use CraftBukkit nowdays? 

I might look what could have a change but Bungee implementation should not throw any errors in bukkit.

**Comment by TryHardDood** [comment]
I don't, but a somebody does. 
You can change `net.md_5.bungee.api.ChatColor` to `org.bukkit.ChatColor` and `net.md_5.bungee.api.plugin.Plugin` to `org.bukkit.plugin.Plugin`. ( Without causing too much trouble. )
But I don't know what will you do with this: `net.md_5.bungee.api.ProxyServer`

**Comment by Blackfire62** [comment]
Its bungee api, you cant change that since its bungee related. Even craftbukkit server does not touch it.

**Comment by TryHardDood** [comment]
Just remove CraftBukkit support, after all, it's a spigot plugin, right?
If you don't want to remove CraftBukkit support check this out:
```
try {
    Class.forName("net.md_5.bungee.api.ProxyServer"); //BungeeApi
    return true;
} catch(Exception e) {
    return false; //Not BungeeApi
}
```
