### ISSUE TITLE
Known issues in 11.7 Alpha [collected]

### ISSUE THREAD

**Issue by Platinteufel** [Th3Tr0LLeR/SkinsRestorer---Maro#90]
- [x] Spigot 1.10 is released, the plugin should be compiled against this version.
- [x] Skins are resetting after 1-2 days. Seems like there's an automatic cache cleaner that removes also skins that are set by _/skin set name_.
- [x] Debug message `[Ljava.lang.Object;@16d429d2` on every skin change.
- [x] Instant skin updating doesn't work if the player has an item in hand. Seems like there is something wrong with packets. For this reason new players don't have a skin until they relog. **Video:** https://youtu.be/Q8XKokwxtXE 
**In Spigot 1.10 instant skin updating doesn't work at all.**
- [x] Skin updating can cause a clone on bukkit servers because it's not removing the player before adding it again properly. **Video:** https://youtu.be/-Xl5XNj-l-U
![a1346bec-2cd1-11e6-9de7-a47fb486189b](https://cloud.githubusercontent.com/assets/13700636/15937141/048f3260-2e6e-11e6-8b1e-6ee0ec9e4ece.png)
- [x] There are very rare cases where the player is invisible (doesn't see his skin, transparent)
- [x] NPE on some skin updates: http://pastebin.com/qhiu1dAf

**Comment by Blackfire62** [comment]
Everything should be fixed now 
https://github.com/Blackfire62/SkinsRestorer---Maro/blob/master/SkinsRestorer-11.8.jar

**Comment by Platinteufel** [comment]
I will test it, thanks!

**Comment by Platinteufel** [comment]
No problems so far, good job!

**Comment by Blackfire62** [comment]
Alright, let me know if anything, and also others who post old issues from 11.6.1 should be redirrected to latedt version.

**Comment by Augustin37** [comment]
Thank you for the fixes! I just got 1 or 2 problems:

- Some skins don't work (I think it's skins from players that are not linked to a mojang account) : example: "KingTramp"

- After applying a skin that don't work, even if we drop the skin, I am still steve, and I got this error when joining :
```java
[01:52:45 INFO]: UUID of player Augustin37 is 07da5ee5-24d6-3bb0-a576-ab39ef2d9323
[01:52:45 WARN]: java.lang.NullPointerException
[01:52:45 WARN]:        at skinsrestorer.bukkit.UniversalSkinFactory.updateSkin(UniversalSkinFactory.java:152)
[01:52:45 WARN]:        at skinsrestorer.bukkit.UniversalSkinFactory$1.applySkin(UniversalSkinFactory.java:49)
[01:52:45 WARN]:        at skinsrestorer.shared.format.SkinProfile.applySkin(SkinProfile.java:65)
[01:52:45 WARN]:        at skinsrestorer.bukkit.UniversalSkinFactory.applySkin(UniversalSkinFactory.java:29)
[01:52:45 WARN]:        at skinsrestorer.shared.api.SkinsRestorerAPI.applySkin(SkinsRestorerAPI.java:83)
[01:52:45 WARN]:        at skinsrestorer.bukkit.listeners.LoginListener$2.run(LoginListener.java:95)
[01:52:45 WARN]:        at java.lang.Thread.run(Thread.java:745)
[01:52:46 INFO]: Augustin37[/89.87.76.7:57272] logged in with entity id 7272 at ([IronWorld]-7329.564812017121, 104.0, 2382.988527604039)
```

**Comment by Platinteufel** [comment]
Confirmed, a player wasn't able to join the server. There's also this npe in console.

**Comment by Platinteufel** [comment]
Client crash message: http://pastebin.com/gqruNPEJ

**Comment by Blackfire62** [comment]
Well, I can run the skin (http://prntscr.com/beq6x6) . It went off on the second try.
Also I get no errors. And yes, that drop command could use some modifications.

**Comment by Blackfire62** [comment]
I just noticed it, for legacy players there is a small addition in skin data that breaks my patters (so skin data are once again corrupted) . The second try was thru McAPI which doesnt provide that addition, thats why it went right. Will make an update.

**Comment by Blackfire62** [comment]
https://github.com/Blackfire62/SkinsRestorer---Maro/blob/master/SkinsRestorer11.8.1.jar

**Comment by Platinteufel** [comment]
Now I can run the skin 'KingTramp", but there's still this NPE in console:
http://pastebin.com/qhiu1dAf

**Comment by Augustin37** [comment]
Thank you Blackfire :DDDD
I just got the same litte error ^^

**Comment by Blackfire62** [comment]
New update, you can test it out, since I dont even have legal minecraft launcher https://github.com/Blackfire62/SkinsRestorer---Maro/blob/master/SkinsRestorer-11.8.2.jar

**Comment by Platinteufel** [comment]
No issues so far, seems like this is a releasable version. Thank you for your hard work @Blackfire62 :)

**Comment by Augustin37** [comment]
Thank you very much for your time and code blackfire! :D

**Comment by Blackfire62** [comment]
np :D I do it as a programming practise tbh, and also because I hate playing without my skin, everyone should have a skin .

Also, i do it all for free open source, etc..
I do have paypal, but this is not my project so i dont deserve a thing :D .

You can continue to post bugs/ideas in the issues section.
