### ISSUE TITLE
in new version of skins  restorer some skins dont work [fixed in 11.8.3]

### ISSUE THREAD

**Issue by SilentX88** [Th3Tr0LLeR/SkinsRestorer---Maro#93]
Skinrestorer version 11.6.1
Bungeecord dev #1158

Some skins won't show! 
Example skin from player **beecub**
If player try to use skin from **beecub** he get default stive skin.

All of that working perfect in version v10.5.6 , but in new version some skins not workin.

I will remain on version 10.5.6

**Comment by Blackfire62** [comment]
Youre not using the latest version (I released it few minutes ago)
That error has been fixed some time ago
https://github.com/Blackfire62/SkinsRestorer---Maro/blob/master/SkinsRestorer-11.8.3.jar

**Comment by SilentX88** [comment]
oh you are fast man. I will try that later.

**Comment by andris155** [comment]
SkinsBukkitModule new version?

**Comment by Blackfire62** [comment]
Yeah i forgot to mention, SkinsModule is now included in SkinsRestorer.jar and will be enabled if the setting "bungeecord" in spigot.yml is set to true (so only for bungee servers)

**Comment by andris155** [comment]
Thanks. :)

**Comment by SilentX88** [comment]
yeah, all works in version 11.8.3 thx
