### ISSUE TITLE
Skin fetch failed: An error has ocurred

### ISSUE THREAD

**Issue by ashitoman** [Th3Tr0LLeR/SkinsRestorer---Maro#94]
SkinRestorer still not working in my server
I tried /skin set GioYT  (premium account)
![2016-06-13_00 24 42](https://cloud.githubusercontent.com/assets/19341044/15999684/ed57697c-310c-11e6-920c-5b7cc9fe6300.png)

Server Version
*Last build of 1.9.4

SkinRestorer Version
SkinsRestorer-11.8.3

**Comment by Th3Tr0LLeR** [comment]
What about providing some info like debug file ?

**Comment by Blackfire62** [comment]
I just noticed that errors are not translated anymore. That could use a fix

**Comment by ashitoman** [comment]
Th3Tr0LLeR 
how can I activate the debug mode in your plugin?

console capture
![console](https://cloud.githubusercontent.com/assets/19341044/16036595/42e960cc-31e2-11e6-8245-31909c609ace.png)

**Comment by ashitoman** [comment]
Blackfire62
I'm rated limited maybe by your plugin 
![error](https://cloud.githubusercontent.com/assets/19341044/16220208/eb898c52-3750-11e6-9986-210ec13ce2a9.png)

**Comment by Blackfire62** [comment]
If you request the skull of the same name you just requested skin, you have to wait 10 mins for it to didsapear

**Comment by Blackfire62** [comment]
According to method these skulls are requested.
