### ISSUE TITLE
Skin fetch failed: An error has occured: skinsrestorer.shared.utils.SkinFetchUtils$SkinFetchFailedException: Can't find a valid premium player with that name

### ISSUE THREAD

**Issue by MigulixCZ** [Th3Tr0LLeR/SkinsRestorer---Maro#98]
I have premium account.. It's not working for Herobrine, Notch, etc.

**Comment by Boddou** [comment]
Same problem. I hope this bug will be resolved soon!

**Comment by Blackfire62** [comment]
This wont tell me anything, ale you are most likely using outdated version.

**Comment by Boddou** [comment]
I use the latest version uploaded on this github !

**Comment by Blackfire62** [comment]
This one is currently the latest : https://github.com/Blackfire62/SkinsRestorer---Maro/blob/master/SkinsRestorer-11.8.4.jar and which command did you run when you got this command? Any other error logs ? Just one line cant tell me much info if the mentioned player really is premium.

**Comment by Boddou** [comment]
Do /skinsrestorer set PSEUDO SKIN
And username is a premium user (mine)

**Comment by Boddou** [comment]
https://i.gyazo.com/264e429506f81c8c44a5e32ebd2c04a7.png

**Comment by Blackfire62** [comment]
Works fine for me,http://prntscr.com/bhamuc . Have you tried other skins, if they are doing the same error? If so, your connection is probably blocking mojang ips, look up the iptables section on spigot page of SkinsRestorer .

**Comment by Boddou** [comment]
iptables is clean and yes I tried with other player of my server, same error..

**Comment by Blackfire62** [comment]
Then its certainly blocking mojang site, if you are using hosting, try to tak to their support about it.
But just to be sure, you can try /sr debug and paste the debug.txt file somewhere, we will see.

**Comment by Boddou** [comment]
I'm using a dedicated server from SoYouStart

**Comment by Boddou** [comment]
Java version: 1.8.0_91
Bungee version: git:BungeeCord-Bootstrap:1.10-SNAPSHOT:97eef62:1159
SkinsRestoerer version: 11.8.4 (Blackfire62's fork)

Plugin list: reconnect_yaml (git:reconnect_yaml:1.10-SNAPSHOT:97eef62:1159), cmd_find (git:cmd_find:1.10-SNAPSHOT:97eef62:1159), SkinsRestorer (11.8.4 (Blackfire62's fork)), BungeePexBridge (1.5), BungeeAuthMeBridge (1.6), cmd_server (git:cmd_server:1.10-SNAPSHOT:97eef62:1159), cmd_alert (git:cmd_alert:1.10-SNAPSHOT:97eef62:1159), ServerListPlus (3.4.5), cmd_send (git:cmd_send:1.10-SNAPSHOT:97eef62:1159), cmd_list (git:cmd_list:1.10-SNAPSHOT:97eef62:1159), 

Property output from MojangAPI (Boddou) : 
=========================================
skinsrestorer.shared.utils.SkinFetchUtils$SkinFetchFailedException: §cCan't find a valid premium player with that name
	at skinsrestorer.shared.utils.MojangAPI.getProfile(MojangAPI.java:32)
	at skinsrestorer.bungee.commands.AdminCommands$3.run(AdminCommands.java:189)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
=========================================

**Comment by Blackfire62** [comment]
Yeah, thats clearly a null/empty response from Mojang API site, i dont know what could be blocking it for you if you already tried the iptables.

**Comment by Boddou** [comment]
Do you have the api url to curl it please ?

**Comment by Blackfire62** [comment]
These are the urls the plugin is currently accessing:
https://api.mojang.com/users/profiles/minecraft/    // For UUIDs
https://sessionserver.mojang.com/session/minecraft/profile/   //For Skin data
and the mcapi.ca one //For Skin Data

**Comment by Boddou** [comment]
UUIDs: `{"error":"Not Found","errorMessage":"The server has not found anything matching the request URI"}` ... It is normal ?

**Comment by Blackfire62** [comment]
Yes, and if you add a premium nickname after the last slash you should get a nice json string containing UUID and player name. 

Non-premium nicknames return nothing.

**Comment by Boddou** [comment]
I'm a premium user but it's returning nothing..

**Comment by Blackfire62** [comment]
http://prntscr.com/bhb3f7 An example.
 If it returns nothing for premium players, I dont know what could be wrong and I cant do anything about it.

**Comment by Boddou** [comment]
Huh ok i've misunderstanded the uri format ^^
When I curl `https://api.mojang.com/users/profiles/minecraft/Boddou` from my dedicated server, return this:
`{"id":"7f8370aaa46a4f51b5fc51249f961e7f","name":"Boddou"}`
But in game, no skins :/

**Comment by Boddou** [comment]
Not any bungee plugins compatibility problem with SR ?

**Comment by Boddou** [comment]
Url seems broken here:
`MCAPI:
  Enabled: true
  Get Profile URL: https://mcapi.ca/SR/?player\u003d{username}
  Get SkinProfile URL: https://mcapi.ca/name/uuid/{uuid}`

**Comment by Boddou** [comment]
Okay it's seems to be MCAPI down right now..
